// Code generated by enumgen from keywords.yml. DO NOT EDIT.

package enums

import (
	"fmt"
	"iter"
	"strings"
)

// Keyword is a string-wide identifier. The zero-cost conversion Keyword(x) is
// intentional: the underlying value is the wire value.
type Keyword string

const (
	KeywordVar         Keyword = "Var"
	KeywordIf          Keyword = "If"
	KeywordElse        Keyword = "Else"
	KeywordFor         Keyword = "For"
	KeywordBreak       Keyword = "Break"
	KeywordContinue    Keyword = "Continue"
	KeywordReturn      Keyword = "Return"
	KeywordFunc        Keyword = "Func"
	KeywordTrue        Keyword = "True"
	KeywordFalse       Keyword = "False"
	KeywordStruct      Keyword = "Struct"
	KeywordThis        Keyword = "This"
	KeywordImport      Keyword = "Import"
	KeywordConstructor Keyword = "Constructor"
	KeywordDestructor  Keyword = "Destructor"
	KeywordNew         Keyword = "New"
	KeywordDelete      Keyword = "Delete"
	KeywordExtern      Keyword = "Extern"
	KeywordMap         Keyword = "Map"
	KeywordEnum        Keyword = "Enum"
	KeywordMatch       Keyword = "Match"
	KeywordYield       Keyword = "Yield"
	KeywordRange       Keyword = "Range"
	KeywordAsync       Keyword = "Async"
	KeywordAwait       Keyword = "Await"
)

type KeywordContainer struct {
	Var         Keyword
	If          Keyword
	Else        Keyword
	For         Keyword
	Break       Keyword
	Continue    Keyword
	Return      Keyword
	Func        Keyword
	True        Keyword
	False       Keyword
	Struct      Keyword
	This        Keyword
	Import      Keyword
	Constructor Keyword
	Destructor  Keyword
	New         Keyword
	Delete      Keyword
	Extern      Keyword
	Map         Keyword
	Enum        Keyword
	Match       Keyword
	Yield       Keyword
	Range       Keyword
	Async       Keyword
	Await       Keyword
}

// Keywords is the entry point for the Keyword enum.
var Keywords = KeywordContainer{
	Var:         KeywordVar,
	If:          KeywordIf,
	Else:        KeywordElse,
	For:         KeywordFor,
	Break:       KeywordBreak,
	Continue:    KeywordContinue,
	Return:      KeywordReturn,
	Func:        KeywordFunc,
	True:        KeywordTrue,
	False:       KeywordFalse,
	Struct:      KeywordStruct,
	This:        KeywordThis,
	Import:      KeywordImport,
	Constructor: KeywordConstructor,
	Destructor:  KeywordDestructor,
	New:         KeywordNew,
	Delete:      KeywordDelete,
	Extern:      KeywordExtern,
	Map:         KeywordMap,
	Enum:        KeywordEnum,
	Match:       KeywordMatch,
	Yield:       KeywordYield,
	Range:       KeywordRange,
	Async:       KeywordAsync,
	Await:       KeywordAwait,
}

// KeywordInfo is the static metadata attached to a Keyword.
type KeywordInfo struct {
	Keyword
	Name   string
	String string
}

var keywordInfos = map[Keyword]KeywordInfo{
	KeywordVar: {
		Keyword: KeywordVar,
		Name:    "Var",
		String:  "var",
	},
	KeywordIf: {
		Keyword: KeywordIf,
		Name:    "If",
		String:  "if",
	},
	KeywordElse: {
		Keyword: KeywordElse,
		Name:    "Else",
		String:  "else",
	},
	KeywordFor: {
		Keyword: KeywordFor,
		Name:    "For",
		String:  "for",
	},
	KeywordBreak: {
		Keyword: KeywordBreak,
		Name:    "Break",
		String:  "break",
	},
	KeywordContinue: {
		Keyword: KeywordContinue,
		Name:    "Continue",
		String:  "continue",
	},
	KeywordReturn: {
		Keyword: KeywordReturn,
		Name:    "Return",
		String:  "return",
	},
	KeywordFunc: {
		Keyword: KeywordFunc,
		Name:    "Func",
		String:  "func",
	},
	KeywordTrue: {
		Keyword: KeywordTrue,
		Name:    "True",
		String:  "true",
	},
	KeywordFalse: {
		Keyword: KeywordFalse,
		Name:    "False",
		String:  "false",
	},
	KeywordStruct: {
		Keyword: KeywordStruct,
		Name:    "Struct",
		String:  "struct",
	},
	KeywordThis: {
		Keyword: KeywordThis,
		Name:    "This",
		String:  "this",
	},
	KeywordImport: {
		Keyword: KeywordImport,
		Name:    "Import",
		String:  "import",
	},
	KeywordConstructor: {
		Keyword: KeywordConstructor,
		Name:    "Constructor",
		String:  "constructor",
	},
	KeywordDestructor: {
		Keyword: KeywordDestructor,
		Name:    "Destructor",
		String:  "destructor",
	},
	KeywordNew: {
		Keyword: KeywordNew,
		Name:    "New",
		String:  "new",
	},
	KeywordDelete: {
		Keyword: KeywordDelete,
		Name:    "Delete",
		String:  "delete",
	},
	KeywordExtern: {
		Keyword: KeywordExtern,
		Name:    "Extern",
		String:  "extern",
	},
	KeywordMap: {
		Keyword: KeywordMap,
		Name:    "Map",
		String:  "map",
	},
	KeywordEnum: {
		Keyword: KeywordEnum,
		Name:    "Enum",
		String:  "enum",
	},
	KeywordMatch: {
		Keyword: KeywordMatch,
		Name:    "Match",
		String:  "match",
	},
	KeywordYield: {
		Keyword: KeywordYield,
		Name:    "Yield",
		String:  "yield",
	},
	KeywordRange: {
		Keyword: KeywordRange,
		Name:    "Range",
		String:  "range",
	},
	KeywordAsync: {
		Keyword: KeywordAsync,
		Name:    "Async",
		String:  "async",
	},
	KeywordAwait: {
		Keyword: KeywordAwait,
		Name:    "Await",
		String:  "await",
	},
}

var keywordValues = []Keyword{
	KeywordVar,
	KeywordIf,
	KeywordElse,
	KeywordFor,
	KeywordBreak,
	KeywordContinue,
	KeywordReturn,
	KeywordFunc,
	KeywordTrue,
	KeywordFalse,
	KeywordStruct,
	KeywordThis,
	KeywordImport,
	KeywordConstructor,
	KeywordDestructor,
	KeywordNew,
	KeywordDelete,
	KeywordExtern,
	KeywordMap,
	KeywordEnum,
	KeywordMatch,
	KeywordYield,
	KeywordRange,
	KeywordAsync,
	KeywordAwait,
}

var keywordByName = map[string]Keyword{
	"var":         KeywordVar,
	"if":          KeywordIf,
	"else":        KeywordElse,
	"for":         KeywordFor,
	"break":       KeywordBreak,
	"continue":    KeywordContinue,
	"return":      KeywordReturn,
	"func":        KeywordFunc,
	"true":        KeywordTrue,
	"false":       KeywordFalse,
	"struct":      KeywordStruct,
	"this":        KeywordThis,
	"import":      KeywordImport,
	"constructor": KeywordConstructor,
	"destructor":  KeywordDestructor,
	"new":         KeywordNew,
	"delete":      KeywordDelete,
	"extern":      KeywordExtern,
	"map":         KeywordMap,
	"enum":        KeywordEnum,
	"match":       KeywordMatch,
	"yield":       KeywordYield,
	"range":       KeywordRange,
	"async":       KeywordAsync,
	"await":       KeywordAwait,
}

// Values returns every declared value in declaration order.
func (c KeywordContainer) Values() []Keyword {
	out := make([]Keyword, len(keywordValues))
	copy(out, keywordValues)
	return out
}

// Infos returns every declared value's metadata in declaration order.
func (c KeywordContainer) Infos() []KeywordInfo {
	out := make([]KeywordInfo, len(keywordValues))
	for i, v := range keywordValues {
		out[i] = keywordInfos[v]
	}
	return out
}

// Len returns the number of declared values.
func (c KeywordContainer) Len() int {
	return len(keywordValues)
}

// All iterates every declared value in declaration order.
func (c KeywordContainer) All() iter.Seq[Keyword] {
	return func(yield func(Keyword) bool) {
		for _, v := range keywordValues {
			if !yield(v) {
				return
			}
		}
	}
}

// FromWire converts a raw wire value, reporting whether it is declared.
func (c KeywordContainer) FromWire(w string) (Keyword, bool) {
	v := Keyword(w)
	_, ok := keywordInfos[v]
	return v, ok
}

// FromWireUnsafe converts a raw wire value, assuming it's declared.
func (c KeywordContainer) FromWireUnsafe(w string) Keyword {
	return Keyword(w)
}

// Parse resolves a value by name, case-insensitively.
func (c KeywordContainer) Parse(s string) (Keyword, error) {
	if v, ok := keywordByName[strings.ToLower(strings.TrimSpace(s))]; ok {
		return v, nil
	}
	var zero Keyword
	return zero, fmt.Errorf("unknown Keyword: %q", s)
}

// TryGetInfo returns the metadata for v, and whether v is a declared value.
func (v Keyword) TryGetInfo() (KeywordInfo, bool) {
	i, ok := keywordInfos[v]
	return i, ok
}

// Info returns the metadata for v, and whether v is a declared value.
func (v Keyword) Info() KeywordInfo {
	return keywordInfos[v]
}

func (v Keyword) Valid() bool {
	_, ok := keywordInfos[v]
	return ok
}

func (v Keyword) Wire() string {
	return string(v)
}

func (v Keyword) Name() string {
	return keywordInfos[v].Name
}

func (v Keyword) String() string {
	if i, ok := keywordInfos[v]; ok {
		return i.Name
	}
	return fmt.Sprintf("Keyword(%q)", string(v))
}
