// Code generated by enumgen from lexemes.yml. DO NOT EDIT.

package enums

import (
	"fmt"
	"iter"
	"strings"
)

// Lexeme is a int-wide identifier. The zero-cost conversion Lexeme(x) is
// intentional: the underlying value is the wire value.
type Lexeme int

const (
	LexemeNumber           Lexeme = 0
	LexemeIdentifier       Lexeme = 1
	LexemeString           Lexeme = 2
	LexemePlus             Lexeme = 3
	LexemeMinus            Lexeme = 4
	LexemeSlash            Lexeme = 5
	LexemeAsterisk         Lexeme = 6
	LexemePercent          Lexeme = 7
	LexemeCaret            Lexeme = 8
	LexemeLeftParen        Lexeme = 9
	LexemeRightParen       Lexeme = 10
	LexemeComma            Lexeme = 11
	LexemeDot              Lexeme = 12
	LexemeDotDotDot        Lexeme = 13
	LexemeColon            Lexeme = 14
	LexemeSemicolon        Lexeme = 15
	LexemeEqual            Lexeme = 16
	LexemeLessThan         Lexeme = 17
	LexemeGreaterThan      Lexeme = 18
	LexemeLessThanEqual    Lexeme = 19
	LexemeGreaterThanEqual Lexeme = 20
	LexemeNotEqual         Lexeme = 21
	LexemeAnd              Lexeme = 22
	LexemeOr               Lexeme = 23
	LexemeNot              Lexeme = 24
	LexemeQuestion         Lexeme = 25
	LexemeLeftBracket      Lexeme = 26
	LexemeRightBracket     Lexeme = 27
	LexemeLeftBrace        Lexeme = 28
	LexemeRightBrace       Lexeme = 29
	LexemeColonEqual       Lexeme = 30
	LexemeEqualEqual       Lexeme = 31
	LexemeFatArrow         Lexeme = 32
	LexemePlusPlus         Lexeme = 33
	LexemeMinusMinus       Lexeme = 34
	LexemePlusEqual        Lexeme = 35
	LexemeMinusEqual       Lexeme = 36
	LexemeAsteriskEqual    Lexeme = 37
	LexemeSlashEqual       Lexeme = 38
	LexemeAmpersand        Lexeme = 39
	LexemePipe             Lexeme = 40
	LexemeEOF              Lexeme = 41
	LexemeIllegal          Lexeme = 42
)

type LexemeContainer struct {
	Number           Lexeme
	Identifier       Lexeme
	String           Lexeme
	Plus             Lexeme
	Minus            Lexeme
	Slash            Lexeme
	Asterisk         Lexeme
	Percent          Lexeme
	Caret            Lexeme
	LeftParen        Lexeme
	RightParen       Lexeme
	Comma            Lexeme
	Dot              Lexeme
	DotDotDot        Lexeme
	Colon            Lexeme
	Semicolon        Lexeme
	Equal            Lexeme
	LessThan         Lexeme
	GreaterThan      Lexeme
	LessThanEqual    Lexeme
	GreaterThanEqual Lexeme
	NotEqual         Lexeme
	And              Lexeme
	Or               Lexeme
	Not              Lexeme
	Question         Lexeme
	LeftBracket      Lexeme
	RightBracket     Lexeme
	LeftBrace        Lexeme
	RightBrace       Lexeme
	ColonEqual       Lexeme
	EqualEqual       Lexeme
	FatArrow         Lexeme
	PlusPlus         Lexeme
	MinusMinus       Lexeme
	PlusEqual        Lexeme
	MinusEqual       Lexeme
	AsteriskEqual    Lexeme
	SlashEqual       Lexeme
	Ampersand        Lexeme
	Pipe             Lexeme
	EOF              Lexeme
	Illegal          Lexeme
}

// Lexemes is the entry point for the Lexeme enum.
var Lexemes = LexemeContainer{
	Number:           LexemeNumber,
	Identifier:       LexemeIdentifier,
	String:           LexemeString,
	Plus:             LexemePlus,
	Minus:            LexemeMinus,
	Slash:            LexemeSlash,
	Asterisk:         LexemeAsterisk,
	Percent:          LexemePercent,
	Caret:            LexemeCaret,
	LeftParen:        LexemeLeftParen,
	RightParen:       LexemeRightParen,
	Comma:            LexemeComma,
	Dot:              LexemeDot,
	DotDotDot:        LexemeDotDotDot,
	Colon:            LexemeColon,
	Semicolon:        LexemeSemicolon,
	Equal:            LexemeEqual,
	LessThan:         LexemeLessThan,
	GreaterThan:      LexemeGreaterThan,
	LessThanEqual:    LexemeLessThanEqual,
	GreaterThanEqual: LexemeGreaterThanEqual,
	NotEqual:         LexemeNotEqual,
	And:              LexemeAnd,
	Or:               LexemeOr,
	Not:              LexemeNot,
	Question:         LexemeQuestion,
	LeftBracket:      LexemeLeftBracket,
	RightBracket:     LexemeRightBracket,
	LeftBrace:        LexemeLeftBrace,
	RightBrace:       LexemeRightBrace,
	ColonEqual:       LexemeColonEqual,
	EqualEqual:       LexemeEqualEqual,
	FatArrow:         LexemeFatArrow,
	PlusPlus:         LexemePlusPlus,
	MinusMinus:       LexemeMinusMinus,
	PlusEqual:        LexemePlusEqual,
	MinusEqual:       LexemeMinusEqual,
	AsteriskEqual:    LexemeAsteriskEqual,
	SlashEqual:       LexemeSlashEqual,
	Ampersand:        LexemeAmpersand,
	Pipe:             LexemePipe,
	EOF:              LexemeEOF,
	Illegal:          LexemeIllegal,
}

// LexemeInfo is the static metadata attached to a Lexeme.
type LexemeInfo struct {
	Lexeme
	Name string
	Char string
}

var lexemeInfos = map[Lexeme]LexemeInfo{
	LexemeNumber: {
		Lexeme: LexemeNumber,
		Name:   "Number",
		Char:   "",
	},
	LexemeIdentifier: {
		Lexeme: LexemeIdentifier,
		Name:   "Identifier",
		Char:   "",
	},
	LexemeString: {
		Lexeme: LexemeString,
		Name:   "String",
		Char:   "",
	},
	LexemePlus: {
		Lexeme: LexemePlus,
		Name:   "Plus",
		Char:   "+",
	},
	LexemeMinus: {
		Lexeme: LexemeMinus,
		Name:   "Minus",
		Char:   "-",
	},
	LexemeSlash: {
		Lexeme: LexemeSlash,
		Name:   "Slash",
		Char:   "/",
	},
	LexemeAsterisk: {
		Lexeme: LexemeAsterisk,
		Name:   "Asterisk",
		Char:   "*",
	},
	LexemePercent: {
		Lexeme: LexemePercent,
		Name:   "Percent",
		Char:   "%",
	},
	LexemeCaret: {
		Lexeme: LexemeCaret,
		Name:   "Caret",
		Char:   "^",
	},
	LexemeLeftParen: {
		Lexeme: LexemeLeftParen,
		Name:   "LeftParen",
		Char:   "(",
	},
	LexemeRightParen: {
		Lexeme: LexemeRightParen,
		Name:   "RightParen",
		Char:   ")",
	},
	LexemeComma: {
		Lexeme: LexemeComma,
		Name:   "Comma",
		Char:   ",",
	},
	LexemeDot: {
		Lexeme: LexemeDot,
		Name:   "Dot",
		Char:   ".",
	},
	LexemeDotDotDot: {
		Lexeme: LexemeDotDotDot,
		Name:   "DotDotDot",
		Char:   "...",
	},
	LexemeColon: {
		Lexeme: LexemeColon,
		Name:   "Colon",
		Char:   ":",
	},
	LexemeSemicolon: {
		Lexeme: LexemeSemicolon,
		Name:   "Semicolon",
		Char:   ";",
	},
	LexemeEqual: {
		Lexeme: LexemeEqual,
		Name:   "Equal",
		Char:   "=",
	},
	LexemeLessThan: {
		Lexeme: LexemeLessThan,
		Name:   "LessThan",
		Char:   "<",
	},
	LexemeGreaterThan: {
		Lexeme: LexemeGreaterThan,
		Name:   "GreaterThan",
		Char:   ">",
	},
	LexemeLessThanEqual: {
		Lexeme: LexemeLessThanEqual,
		Name:   "LessThanEqual",
		Char:   "<=",
	},
	LexemeGreaterThanEqual: {
		Lexeme: LexemeGreaterThanEqual,
		Name:   "GreaterThanEqual",
		Char:   ">=",
	},
	LexemeNotEqual: {
		Lexeme: LexemeNotEqual,
		Name:   "NotEqual",
		Char:   "!=",
	},
	LexemeAnd: {
		Lexeme: LexemeAnd,
		Name:   "And",
		Char:   "&&",
	},
	LexemeOr: {
		Lexeme: LexemeOr,
		Name:   "Or",
		Char:   "||",
	},
	LexemeNot: {
		Lexeme: LexemeNot,
		Name:   "Not",
		Char:   "!",
	},
	LexemeQuestion: {
		Lexeme: LexemeQuestion,
		Name:   "Question",
		Char:   "?",
	},
	LexemeLeftBracket: {
		Lexeme: LexemeLeftBracket,
		Name:   "LeftBracket",
		Char:   "[",
	},
	LexemeRightBracket: {
		Lexeme: LexemeRightBracket,
		Name:   "RightBracket",
		Char:   "]",
	},
	LexemeLeftBrace: {
		Lexeme: LexemeLeftBrace,
		Name:   "LeftBrace",
		Char:   "{",
	},
	LexemeRightBrace: {
		Lexeme: LexemeRightBrace,
		Name:   "RightBrace",
		Char:   "}",
	},
	LexemeColonEqual: {
		Lexeme: LexemeColonEqual,
		Name:   "ColonEqual",
		Char:   ":=",
	},
	LexemeEqualEqual: {
		Lexeme: LexemeEqualEqual,
		Name:   "EqualEqual",
		Char:   "==",
	},
	LexemeFatArrow: {
		Lexeme: LexemeFatArrow,
		Name:   "FatArrow",
		Char:   "=>",
	},
	LexemePlusPlus: {
		Lexeme: LexemePlusPlus,
		Name:   "PlusPlus",
		Char:   "++",
	},
	LexemeMinusMinus: {
		Lexeme: LexemeMinusMinus,
		Name:   "MinusMinus",
		Char:   "--",
	},
	LexemePlusEqual: {
		Lexeme: LexemePlusEqual,
		Name:   "PlusEqual",
		Char:   "+=",
	},
	LexemeMinusEqual: {
		Lexeme: LexemeMinusEqual,
		Name:   "MinusEqual",
		Char:   "-=",
	},
	LexemeAsteriskEqual: {
		Lexeme: LexemeAsteriskEqual,
		Name:   "AsteriskEqual",
		Char:   "*=",
	},
	LexemeSlashEqual: {
		Lexeme: LexemeSlashEqual,
		Name:   "SlashEqual",
		Char:   "/=",
	},
	LexemeAmpersand: {
		Lexeme: LexemeAmpersand,
		Name:   "Ampersand",
		Char:   "&",
	},
	LexemePipe: {
		Lexeme: LexemePipe,
		Name:   "Pipe",
		Char:   "|",
	},
	LexemeEOF: {
		Lexeme: LexemeEOF,
		Name:   "EOF",
		Char:   "",
	},
	LexemeIllegal: {
		Lexeme: LexemeIllegal,
		Name:   "Illegal",
		Char:   "",
	},
}

var lexemeValues = []Lexeme{
	LexemeNumber,
	LexemeIdentifier,
	LexemeString,
	LexemePlus,
	LexemeMinus,
	LexemeSlash,
	LexemeAsterisk,
	LexemePercent,
	LexemeCaret,
	LexemeLeftParen,
	LexemeRightParen,
	LexemeComma,
	LexemeDot,
	LexemeDotDotDot,
	LexemeColon,
	LexemeSemicolon,
	LexemeEqual,
	LexemeLessThan,
	LexemeGreaterThan,
	LexemeLessThanEqual,
	LexemeGreaterThanEqual,
	LexemeNotEqual,
	LexemeAnd,
	LexemeOr,
	LexemeNot,
	LexemeQuestion,
	LexemeLeftBracket,
	LexemeRightBracket,
	LexemeLeftBrace,
	LexemeRightBrace,
	LexemeColonEqual,
	LexemeEqualEqual,
	LexemeFatArrow,
	LexemePlusPlus,
	LexemeMinusMinus,
	LexemePlusEqual,
	LexemeMinusEqual,
	LexemeAsteriskEqual,
	LexemeSlashEqual,
	LexemeAmpersand,
	LexemePipe,
	LexemeEOF,
	LexemeIllegal,
}

var lexemeByName = map[string]Lexeme{
	"number":           LexemeNumber,
	"identifier":       LexemeIdentifier,
	"string":           LexemeString,
	"plus":             LexemePlus,
	"minus":            LexemeMinus,
	"slash":            LexemeSlash,
	"asterisk":         LexemeAsterisk,
	"percent":          LexemePercent,
	"caret":            LexemeCaret,
	"leftparen":        LexemeLeftParen,
	"rightparen":       LexemeRightParen,
	"comma":            LexemeComma,
	"dot":              LexemeDot,
	"dotdotdot":        LexemeDotDotDot,
	"colon":            LexemeColon,
	"semicolon":        LexemeSemicolon,
	"equal":            LexemeEqual,
	"lessthan":         LexemeLessThan,
	"greaterthan":      LexemeGreaterThan,
	"lessthanequal":    LexemeLessThanEqual,
	"greaterthanequal": LexemeGreaterThanEqual,
	"notequal":         LexemeNotEqual,
	"and":              LexemeAnd,
	"or":               LexemeOr,
	"not":              LexemeNot,
	"question":         LexemeQuestion,
	"leftbracket":      LexemeLeftBracket,
	"rightbracket":     LexemeRightBracket,
	"leftbrace":        LexemeLeftBrace,
	"rightbrace":       LexemeRightBrace,
	"colonequal":       LexemeColonEqual,
	"equalequal":       LexemeEqualEqual,
	"fatarrow":         LexemeFatArrow,
	"plusplus":         LexemePlusPlus,
	"minusminus":       LexemeMinusMinus,
	"plusequal":        LexemePlusEqual,
	"minusequal":       LexemeMinusEqual,
	"asteriskequal":    LexemeAsteriskEqual,
	"slashequal":       LexemeSlashEqual,
	"ampersand":        LexemeAmpersand,
	"pipe":             LexemePipe,
	"eof":              LexemeEOF,
	"illegal":          LexemeIllegal,
}

// Values returns every declared value in declaration order.
func (c LexemeContainer) Values() []Lexeme {
	out := make([]Lexeme, len(lexemeValues))
	copy(out, lexemeValues)
	return out
}

// Infos returns every declared value's metadata in declaration order.
func (c LexemeContainer) Infos() []LexemeInfo {
	out := make([]LexemeInfo, len(lexemeValues))
	for i, v := range lexemeValues {
		out[i] = lexemeInfos[v]
	}
	return out
}

// Len returns the number of declared values.
func (c LexemeContainer) Len() int {
	return len(lexemeValues)
}

// All iterates every declared value in declaration order.
func (c LexemeContainer) All() iter.Seq[Lexeme] {
	return func(yield func(Lexeme) bool) {
		for _, v := range lexemeValues {
			if !yield(v) {
				return
			}
		}
	}
}

// FromWire converts a raw wire value, reporting whether it is declared.
func (c LexemeContainer) FromWire(w int) (Lexeme, bool) {
	v := Lexeme(w)
	_, ok := lexemeInfos[v]
	return v, ok
}

// FromWireUnsafe converts a raw wire value, assuming it's declared.
func (c LexemeContainer) FromWireUnsafe(w int) Lexeme {
	return Lexeme(w)
}

// Parse resolves a value by name, case-insensitively.
func (c LexemeContainer) Parse(s string) (Lexeme, error) {
	if v, ok := lexemeByName[strings.ToLower(strings.TrimSpace(s))]; ok {
		return v, nil
	}
	var zero Lexeme
	return zero, fmt.Errorf("unknown Lexeme: %q", s)
}

// TryGetInfo returns the metadata for v, and whether v is a declared value.
func (v Lexeme) TryGetInfo() (LexemeInfo, bool) {
	i, ok := lexemeInfos[v]
	return i, ok
}

// Info returns the metadata for v, and whether v is a declared value.
func (v Lexeme) Info() LexemeInfo {
	return lexemeInfos[v]
}

func (v Lexeme) Valid() bool {
	_, ok := lexemeInfos[v]
	return ok
}

func (v Lexeme) Wire() int {
	return int(v)
}

func (v Lexeme) Name() string {
	return lexemeInfos[v].Name
}

func (v Lexeme) String() string {
	if i, ok := lexemeInfos[v]; ok {
		return i.Name
	}
	return fmt.Sprintf("Lexeme(%d)", int(v))
}

func (v Lexeme) Char() string {
	return lexemeInfos[v].Char
}
