// Code generated by enumgen from node_kinds.yml. DO NOT EDIT.

package enums

import (
	"fmt"
	"iter"
	"strings"
)

// NodeKind is a int-wide identifier. The zero-cost conversion NodeKind(x) is
// intentional: the underlying value is the wire value.
type NodeKind int

const (
	NodeKindFile          NodeKind = 0
	NodeKindBad           NodeKind = 1
	NodeKindImportDecl    NodeKind = 2
	NodeKindVarDecl       NodeKind = 3
	NodeKindShortVarDecl  NodeKind = 4
	NodeKindFuncDecl      NodeKind = 5
	NodeKindParamList     NodeKind = 6
	NodeKindParam         NodeKind = 7
	NodeKindStructDecl    NodeKind = 8
	NodeKindField         NodeKind = 9
	NodeKindBlock         NodeKind = 10
	NodeKindExprStmt      NodeKind = 11
	NodeKindReturnStmt    NodeKind = 12
	NodeKindBreakStmt     NodeKind = 13
	NodeKindContinueStmt  NodeKind = 14
	NodeKindIfStmt        NodeKind = 15
	NodeKindForStmt       NodeKind = 16
	NodeKindAssignStmt    NodeKind = 17
	NodeKindIncDecStmt    NodeKind = 18
	NodeKindIdent         NodeKind = 19
	NodeKindNumberLit     NodeKind = 20
	NodeKindStringLit     NodeKind = 21
	NodeKindBoolLit       NodeKind = 22
	NodeKindBinaryExpr    NodeKind = 23
	NodeKindUnaryExpr     NodeKind = 24
	NodeKindCallExpr      NodeKind = 25
	NodeKindParenExpr     NodeKind = 26
	NodeKindIndexExpr     NodeKind = 27
	NodeKindMemberExpr    NodeKind = 28
	NodeKindArrayType     NodeKind = 29
	NodeKindCompositeLit  NodeKind = 30
	NodeKindKeyValueExpr  NodeKind = 31
	NodeKindThisExpr      NodeKind = 32
	NodeKindFuncType      NodeKind = 33
	NodeKindParamTypeList NodeKind = 34
)

type NodeKindContainer struct {
	File          NodeKind
	Bad           NodeKind
	ImportDecl    NodeKind
	VarDecl       NodeKind
	ShortVarDecl  NodeKind
	FuncDecl      NodeKind
	ParamList     NodeKind
	Param         NodeKind
	StructDecl    NodeKind
	Field         NodeKind
	Block         NodeKind
	ExprStmt      NodeKind
	ReturnStmt    NodeKind
	BreakStmt     NodeKind
	ContinueStmt  NodeKind
	IfStmt        NodeKind
	ForStmt       NodeKind
	AssignStmt    NodeKind
	IncDecStmt    NodeKind
	Ident         NodeKind
	NumberLit     NodeKind
	StringLit     NodeKind
	BoolLit       NodeKind
	BinaryExpr    NodeKind
	UnaryExpr     NodeKind
	CallExpr      NodeKind
	ParenExpr     NodeKind
	IndexExpr     NodeKind
	MemberExpr    NodeKind
	ArrayType     NodeKind
	CompositeLit  NodeKind
	KeyValueExpr  NodeKind
	ThisExpr      NodeKind
	FuncType      NodeKind
	ParamTypeList NodeKind
}

// NodeKinds is the entry point for the NodeKind enum.
var NodeKinds = NodeKindContainer{
	File:          NodeKindFile,
	Bad:           NodeKindBad,
	ImportDecl:    NodeKindImportDecl,
	VarDecl:       NodeKindVarDecl,
	ShortVarDecl:  NodeKindShortVarDecl,
	FuncDecl:      NodeKindFuncDecl,
	ParamList:     NodeKindParamList,
	Param:         NodeKindParam,
	StructDecl:    NodeKindStructDecl,
	Field:         NodeKindField,
	Block:         NodeKindBlock,
	ExprStmt:      NodeKindExprStmt,
	ReturnStmt:    NodeKindReturnStmt,
	BreakStmt:     NodeKindBreakStmt,
	ContinueStmt:  NodeKindContinueStmt,
	IfStmt:        NodeKindIfStmt,
	ForStmt:       NodeKindForStmt,
	AssignStmt:    NodeKindAssignStmt,
	IncDecStmt:    NodeKindIncDecStmt,
	Ident:         NodeKindIdent,
	NumberLit:     NodeKindNumberLit,
	StringLit:     NodeKindStringLit,
	BoolLit:       NodeKindBoolLit,
	BinaryExpr:    NodeKindBinaryExpr,
	UnaryExpr:     NodeKindUnaryExpr,
	CallExpr:      NodeKindCallExpr,
	ParenExpr:     NodeKindParenExpr,
	IndexExpr:     NodeKindIndexExpr,
	MemberExpr:    NodeKindMemberExpr,
	ArrayType:     NodeKindArrayType,
	CompositeLit:  NodeKindCompositeLit,
	KeyValueExpr:  NodeKindKeyValueExpr,
	ThisExpr:      NodeKindThisExpr,
	FuncType:      NodeKindFuncType,
	ParamTypeList: NodeKindParamTypeList,
}

// NodeKindInfo is the static metadata attached to a NodeKind.
type NodeKindInfo struct {
	NodeKind
	Name string
}

var nodeKindInfos = map[NodeKind]NodeKindInfo{
	NodeKindFile: {
		NodeKind: NodeKindFile,
		Name:     "File",
	},
	NodeKindBad: {
		NodeKind: NodeKindBad,
		Name:     "Bad",
	},
	NodeKindImportDecl: {
		NodeKind: NodeKindImportDecl,
		Name:     "ImportDecl",
	},
	NodeKindVarDecl: {
		NodeKind: NodeKindVarDecl,
		Name:     "VarDecl",
	},
	NodeKindShortVarDecl: {
		NodeKind: NodeKindShortVarDecl,
		Name:     "ShortVarDecl",
	},
	NodeKindFuncDecl: {
		NodeKind: NodeKindFuncDecl,
		Name:     "FuncDecl",
	},
	NodeKindParamList: {
		NodeKind: NodeKindParamList,
		Name:     "ParamList",
	},
	NodeKindParam: {
		NodeKind: NodeKindParam,
		Name:     "Param",
	},
	NodeKindStructDecl: {
		NodeKind: NodeKindStructDecl,
		Name:     "StructDecl",
	},
	NodeKindField: {
		NodeKind: NodeKindField,
		Name:     "Field",
	},
	NodeKindBlock: {
		NodeKind: NodeKindBlock,
		Name:     "Block",
	},
	NodeKindExprStmt: {
		NodeKind: NodeKindExprStmt,
		Name:     "ExprStmt",
	},
	NodeKindReturnStmt: {
		NodeKind: NodeKindReturnStmt,
		Name:     "ReturnStmt",
	},
	NodeKindBreakStmt: {
		NodeKind: NodeKindBreakStmt,
		Name:     "BreakStmt",
	},
	NodeKindContinueStmt: {
		NodeKind: NodeKindContinueStmt,
		Name:     "ContinueStmt",
	},
	NodeKindIfStmt: {
		NodeKind: NodeKindIfStmt,
		Name:     "IfStmt",
	},
	NodeKindForStmt: {
		NodeKind: NodeKindForStmt,
		Name:     "ForStmt",
	},
	NodeKindAssignStmt: {
		NodeKind: NodeKindAssignStmt,
		Name:     "AssignStmt",
	},
	NodeKindIncDecStmt: {
		NodeKind: NodeKindIncDecStmt,
		Name:     "IncDecStmt",
	},
	NodeKindIdent: {
		NodeKind: NodeKindIdent,
		Name:     "Ident",
	},
	NodeKindNumberLit: {
		NodeKind: NodeKindNumberLit,
		Name:     "NumberLit",
	},
	NodeKindStringLit: {
		NodeKind: NodeKindStringLit,
		Name:     "StringLit",
	},
	NodeKindBoolLit: {
		NodeKind: NodeKindBoolLit,
		Name:     "BoolLit",
	},
	NodeKindBinaryExpr: {
		NodeKind: NodeKindBinaryExpr,
		Name:     "BinaryExpr",
	},
	NodeKindUnaryExpr: {
		NodeKind: NodeKindUnaryExpr,
		Name:     "UnaryExpr",
	},
	NodeKindCallExpr: {
		NodeKind: NodeKindCallExpr,
		Name:     "CallExpr",
	},
	NodeKindParenExpr: {
		NodeKind: NodeKindParenExpr,
		Name:     "ParenExpr",
	},
	NodeKindIndexExpr: {
		NodeKind: NodeKindIndexExpr,
		Name:     "IndexExpr",
	},
	NodeKindMemberExpr: {
		NodeKind: NodeKindMemberExpr,
		Name:     "MemberExpr",
	},
	NodeKindArrayType: {
		NodeKind: NodeKindArrayType,
		Name:     "ArrayType",
	},
	NodeKindCompositeLit: {
		NodeKind: NodeKindCompositeLit,
		Name:     "CompositeLit",
	},
	NodeKindKeyValueExpr: {
		NodeKind: NodeKindKeyValueExpr,
		Name:     "KeyValueExpr",
	},
	NodeKindThisExpr: {
		NodeKind: NodeKindThisExpr,
		Name:     "ThisExpr",
	},
	NodeKindFuncType: {
		NodeKind: NodeKindFuncType,
		Name:     "FuncType",
	},
	NodeKindParamTypeList: {
		NodeKind: NodeKindParamTypeList,
		Name:     "ParamTypeList",
	},
}

var nodeKindValues = []NodeKind{
	NodeKindFile,
	NodeKindBad,
	NodeKindImportDecl,
	NodeKindVarDecl,
	NodeKindShortVarDecl,
	NodeKindFuncDecl,
	NodeKindParamList,
	NodeKindParam,
	NodeKindStructDecl,
	NodeKindField,
	NodeKindBlock,
	NodeKindExprStmt,
	NodeKindReturnStmt,
	NodeKindBreakStmt,
	NodeKindContinueStmt,
	NodeKindIfStmt,
	NodeKindForStmt,
	NodeKindAssignStmt,
	NodeKindIncDecStmt,
	NodeKindIdent,
	NodeKindNumberLit,
	NodeKindStringLit,
	NodeKindBoolLit,
	NodeKindBinaryExpr,
	NodeKindUnaryExpr,
	NodeKindCallExpr,
	NodeKindParenExpr,
	NodeKindIndexExpr,
	NodeKindMemberExpr,
	NodeKindArrayType,
	NodeKindCompositeLit,
	NodeKindKeyValueExpr,
	NodeKindThisExpr,
	NodeKindFuncType,
	NodeKindParamTypeList,
}

var nodeKindByName = map[string]NodeKind{
	"file":          NodeKindFile,
	"bad":           NodeKindBad,
	"importdecl":    NodeKindImportDecl,
	"vardecl":       NodeKindVarDecl,
	"shortvardecl":  NodeKindShortVarDecl,
	"funcdecl":      NodeKindFuncDecl,
	"paramlist":     NodeKindParamList,
	"param":         NodeKindParam,
	"structdecl":    NodeKindStructDecl,
	"field":         NodeKindField,
	"block":         NodeKindBlock,
	"exprstmt":      NodeKindExprStmt,
	"returnstmt":    NodeKindReturnStmt,
	"breakstmt":     NodeKindBreakStmt,
	"continuestmt":  NodeKindContinueStmt,
	"ifstmt":        NodeKindIfStmt,
	"forstmt":       NodeKindForStmt,
	"assignstmt":    NodeKindAssignStmt,
	"incdecstmt":    NodeKindIncDecStmt,
	"ident":         NodeKindIdent,
	"numberlit":     NodeKindNumberLit,
	"stringlit":     NodeKindStringLit,
	"boollit":       NodeKindBoolLit,
	"binaryexpr":    NodeKindBinaryExpr,
	"unaryexpr":     NodeKindUnaryExpr,
	"callexpr":      NodeKindCallExpr,
	"parenexpr":     NodeKindParenExpr,
	"indexexpr":     NodeKindIndexExpr,
	"memberexpr":    NodeKindMemberExpr,
	"arraytype":     NodeKindArrayType,
	"compositelit":  NodeKindCompositeLit,
	"keyvalueexpr":  NodeKindKeyValueExpr,
	"thisexpr":      NodeKindThisExpr,
	"functype":      NodeKindFuncType,
	"paramtypelist": NodeKindParamTypeList,
}

// Values returns every declared value in declaration order.
func (c NodeKindContainer) Values() []NodeKind {
	out := make([]NodeKind, len(nodeKindValues))
	copy(out, nodeKindValues)
	return out
}

// Infos returns every declared value's metadata in declaration order.
func (c NodeKindContainer) Infos() []NodeKindInfo {
	out := make([]NodeKindInfo, len(nodeKindValues))
	for i, v := range nodeKindValues {
		out[i] = nodeKindInfos[v]
	}
	return out
}

// Len returns the number of declared values.
func (c NodeKindContainer) Len() int {
	return len(nodeKindValues)
}

// All iterates every declared value in declaration order.
func (c NodeKindContainer) All() iter.Seq[NodeKind] {
	return func(yield func(NodeKind) bool) {
		for _, v := range nodeKindValues {
			if !yield(v) {
				return
			}
		}
	}
}

// FromWire converts a raw wire value, reporting whether it is declared.
func (c NodeKindContainer) FromWire(w int) (NodeKind, bool) {
	v := NodeKind(w)
	_, ok := nodeKindInfos[v]
	return v, ok
}

// FromWireUnsafe converts a raw wire value, assuming it's declared.
func (c NodeKindContainer) FromWireUnsafe(w int) NodeKind {
	return NodeKind(w)
}

// Parse resolves a value by name, case-insensitively.
func (c NodeKindContainer) Parse(s string) (NodeKind, error) {
	if v, ok := nodeKindByName[strings.ToLower(strings.TrimSpace(s))]; ok {
		return v, nil
	}
	var zero NodeKind
	return zero, fmt.Errorf("unknown NodeKind: %q", s)
}

// TryGetInfo returns the metadata for v, and whether v is a declared value.
func (v NodeKind) TryGetInfo() (NodeKindInfo, bool) {
	i, ok := nodeKindInfos[v]
	return i, ok
}

// Info returns the metadata for v, and whether v is a declared value.
func (v NodeKind) Info() NodeKindInfo {
	return nodeKindInfos[v]
}

func (v NodeKind) Valid() bool {
	_, ok := nodeKindInfos[v]
	return ok
}

func (v NodeKind) Wire() int {
	return int(v)
}

func (v NodeKind) Name() string {
	return nodeKindInfos[v].Name
}

func (v NodeKind) String() string {
	if i, ok := nodeKindInfos[v]; ok {
		return i.Name
	}
	return fmt.Sprintf("NodeKind(%d)", int(v))
}
