// Code generated by enumgen from node_kinds.yml. DO NOT EDIT.

package enums

import (
	"fmt"
	"iter"
	"strings"
)

// NodeKind is a int-wide identifier. The zero-cost conversion NodeKind(x) is
// intentional: the underlying value is the wire value.
type NodeKind int

const (
	NodeKindFile              NodeKind = 0
	NodeKindBad               NodeKind = 1
	NodeKindImportDecl        NodeKind = 2
	NodeKindVarDecl           NodeKind = 3
	NodeKindShortVarDecl      NodeKind = 4
	NodeKindFuncDecl          NodeKind = 5
	NodeKindParamList         NodeKind = 6
	NodeKindParam             NodeKind = 7
	NodeKindStructDecl        NodeKind = 8
	NodeKindField             NodeKind = 9
	NodeKindConstructorDecl   NodeKind = 10
	NodeKindDestructorDecl    NodeKind = 11
	NodeKindBlock             NodeKind = 12
	NodeKindExprStmt          NodeKind = 13
	NodeKindReturnStmt        NodeKind = 14
	NodeKindBreakStmt         NodeKind = 15
	NodeKindContinueStmt      NodeKind = 16
	NodeKindIfStmt            NodeKind = 17
	NodeKindForStmt           NodeKind = 18
	NodeKindAssignStmt        NodeKind = 19
	NodeKindIncDecStmt        NodeKind = 20
	NodeKindIdent             NodeKind = 21
	NodeKindNumberLit         NodeKind = 22
	NodeKindStringLit         NodeKind = 23
	NodeKindBoolLit           NodeKind = 24
	NodeKindBinaryExpr        NodeKind = 25
	NodeKindUnaryExpr         NodeKind = 26
	NodeKindCallExpr          NodeKind = 27
	NodeKindParenExpr         NodeKind = 28
	NodeKindIndexExpr         NodeKind = 29
	NodeKindMemberExpr        NodeKind = 30
	NodeKindArrayType         NodeKind = 31
	NodeKindCompositeLit      NodeKind = 32
	NodeKindKeyValueExpr      NodeKind = 33
	NodeKindThisExpr          NodeKind = 34
	NodeKindFuncType          NodeKind = 35
	NodeKindParamTypeList     NodeKind = 36
	NodeKindFuncLit           NodeKind = 37
	NodeKindPointerType       NodeKind = 38
	NodeKindNewExpr           NodeKind = 39
	NodeKindDeleteStmt        NodeKind = 40
	NodeKindSliceExpr         NodeKind = 41
	NodeKindExternFuncDecl    NodeKind = 42
	NodeKindMultiReturnType   NodeKind = 43
	NodeKindMultiValueExpr    NodeKind = 44
	NodeKindMultiShortVarDecl NodeKind = 45
	NodeKindMultiAssignStmt   NodeKind = 46
)

type NodeKindContainer struct {
	File              NodeKind
	Bad               NodeKind
	ImportDecl        NodeKind
	VarDecl           NodeKind
	ShortVarDecl      NodeKind
	FuncDecl          NodeKind
	ParamList         NodeKind
	Param             NodeKind
	StructDecl        NodeKind
	Field             NodeKind
	ConstructorDecl   NodeKind
	DestructorDecl    NodeKind
	Block             NodeKind
	ExprStmt          NodeKind
	ReturnStmt        NodeKind
	BreakStmt         NodeKind
	ContinueStmt      NodeKind
	IfStmt            NodeKind
	ForStmt           NodeKind
	AssignStmt        NodeKind
	IncDecStmt        NodeKind
	Ident             NodeKind
	NumberLit         NodeKind
	StringLit         NodeKind
	BoolLit           NodeKind
	BinaryExpr        NodeKind
	UnaryExpr         NodeKind
	CallExpr          NodeKind
	ParenExpr         NodeKind
	IndexExpr         NodeKind
	MemberExpr        NodeKind
	ArrayType         NodeKind
	CompositeLit      NodeKind
	KeyValueExpr      NodeKind
	ThisExpr          NodeKind
	FuncType          NodeKind
	ParamTypeList     NodeKind
	FuncLit           NodeKind
	PointerType       NodeKind
	NewExpr           NodeKind
	DeleteStmt        NodeKind
	SliceExpr         NodeKind
	ExternFuncDecl    NodeKind
	MultiReturnType   NodeKind
	MultiValueExpr    NodeKind
	MultiShortVarDecl NodeKind
	MultiAssignStmt   NodeKind
}

// NodeKinds is the entry point for the NodeKind enum.
var NodeKinds = NodeKindContainer{
	File:              NodeKindFile,
	Bad:               NodeKindBad,
	ImportDecl:        NodeKindImportDecl,
	VarDecl:           NodeKindVarDecl,
	ShortVarDecl:      NodeKindShortVarDecl,
	FuncDecl:          NodeKindFuncDecl,
	ParamList:         NodeKindParamList,
	Param:             NodeKindParam,
	StructDecl:        NodeKindStructDecl,
	Field:             NodeKindField,
	ConstructorDecl:   NodeKindConstructorDecl,
	DestructorDecl:    NodeKindDestructorDecl,
	Block:             NodeKindBlock,
	ExprStmt:          NodeKindExprStmt,
	ReturnStmt:        NodeKindReturnStmt,
	BreakStmt:         NodeKindBreakStmt,
	ContinueStmt:      NodeKindContinueStmt,
	IfStmt:            NodeKindIfStmt,
	ForStmt:           NodeKindForStmt,
	AssignStmt:        NodeKindAssignStmt,
	IncDecStmt:        NodeKindIncDecStmt,
	Ident:             NodeKindIdent,
	NumberLit:         NodeKindNumberLit,
	StringLit:         NodeKindStringLit,
	BoolLit:           NodeKindBoolLit,
	BinaryExpr:        NodeKindBinaryExpr,
	UnaryExpr:         NodeKindUnaryExpr,
	CallExpr:          NodeKindCallExpr,
	ParenExpr:         NodeKindParenExpr,
	IndexExpr:         NodeKindIndexExpr,
	MemberExpr:        NodeKindMemberExpr,
	ArrayType:         NodeKindArrayType,
	CompositeLit:      NodeKindCompositeLit,
	KeyValueExpr:      NodeKindKeyValueExpr,
	ThisExpr:          NodeKindThisExpr,
	FuncType:          NodeKindFuncType,
	ParamTypeList:     NodeKindParamTypeList,
	FuncLit:           NodeKindFuncLit,
	PointerType:       NodeKindPointerType,
	NewExpr:           NodeKindNewExpr,
	DeleteStmt:        NodeKindDeleteStmt,
	SliceExpr:         NodeKindSliceExpr,
	ExternFuncDecl:    NodeKindExternFuncDecl,
	MultiReturnType:   NodeKindMultiReturnType,
	MultiValueExpr:    NodeKindMultiValueExpr,
	MultiShortVarDecl: NodeKindMultiShortVarDecl,
	MultiAssignStmt:   NodeKindMultiAssignStmt,
}

// NodeKindInfo is the static metadata attached to a NodeKind.
type NodeKindInfo struct {
	NodeKind
	Name string
}

var nodeKindInfos = map[NodeKind]NodeKindInfo{
	NodeKindFile: {
		NodeKind: NodeKindFile,
		Name:     "File",
	},
	NodeKindBad: {
		NodeKind: NodeKindBad,
		Name:     "Bad",
	},
	NodeKindImportDecl: {
		NodeKind: NodeKindImportDecl,
		Name:     "ImportDecl",
	},
	NodeKindVarDecl: {
		NodeKind: NodeKindVarDecl,
		Name:     "VarDecl",
	},
	NodeKindShortVarDecl: {
		NodeKind: NodeKindShortVarDecl,
		Name:     "ShortVarDecl",
	},
	NodeKindFuncDecl: {
		NodeKind: NodeKindFuncDecl,
		Name:     "FuncDecl",
	},
	NodeKindParamList: {
		NodeKind: NodeKindParamList,
		Name:     "ParamList",
	},
	NodeKindParam: {
		NodeKind: NodeKindParam,
		Name:     "Param",
	},
	NodeKindStructDecl: {
		NodeKind: NodeKindStructDecl,
		Name:     "StructDecl",
	},
	NodeKindField: {
		NodeKind: NodeKindField,
		Name:     "Field",
	},
	NodeKindConstructorDecl: {
		NodeKind: NodeKindConstructorDecl,
		Name:     "ConstructorDecl",
	},
	NodeKindDestructorDecl: {
		NodeKind: NodeKindDestructorDecl,
		Name:     "DestructorDecl",
	},
	NodeKindBlock: {
		NodeKind: NodeKindBlock,
		Name:     "Block",
	},
	NodeKindExprStmt: {
		NodeKind: NodeKindExprStmt,
		Name:     "ExprStmt",
	},
	NodeKindReturnStmt: {
		NodeKind: NodeKindReturnStmt,
		Name:     "ReturnStmt",
	},
	NodeKindBreakStmt: {
		NodeKind: NodeKindBreakStmt,
		Name:     "BreakStmt",
	},
	NodeKindContinueStmt: {
		NodeKind: NodeKindContinueStmt,
		Name:     "ContinueStmt",
	},
	NodeKindIfStmt: {
		NodeKind: NodeKindIfStmt,
		Name:     "IfStmt",
	},
	NodeKindForStmt: {
		NodeKind: NodeKindForStmt,
		Name:     "ForStmt",
	},
	NodeKindAssignStmt: {
		NodeKind: NodeKindAssignStmt,
		Name:     "AssignStmt",
	},
	NodeKindIncDecStmt: {
		NodeKind: NodeKindIncDecStmt,
		Name:     "IncDecStmt",
	},
	NodeKindIdent: {
		NodeKind: NodeKindIdent,
		Name:     "Ident",
	},
	NodeKindNumberLit: {
		NodeKind: NodeKindNumberLit,
		Name:     "NumberLit",
	},
	NodeKindStringLit: {
		NodeKind: NodeKindStringLit,
		Name:     "StringLit",
	},
	NodeKindBoolLit: {
		NodeKind: NodeKindBoolLit,
		Name:     "BoolLit",
	},
	NodeKindBinaryExpr: {
		NodeKind: NodeKindBinaryExpr,
		Name:     "BinaryExpr",
	},
	NodeKindUnaryExpr: {
		NodeKind: NodeKindUnaryExpr,
		Name:     "UnaryExpr",
	},
	NodeKindCallExpr: {
		NodeKind: NodeKindCallExpr,
		Name:     "CallExpr",
	},
	NodeKindParenExpr: {
		NodeKind: NodeKindParenExpr,
		Name:     "ParenExpr",
	},
	NodeKindIndexExpr: {
		NodeKind: NodeKindIndexExpr,
		Name:     "IndexExpr",
	},
	NodeKindMemberExpr: {
		NodeKind: NodeKindMemberExpr,
		Name:     "MemberExpr",
	},
	NodeKindArrayType: {
		NodeKind: NodeKindArrayType,
		Name:     "ArrayType",
	},
	NodeKindCompositeLit: {
		NodeKind: NodeKindCompositeLit,
		Name:     "CompositeLit",
	},
	NodeKindKeyValueExpr: {
		NodeKind: NodeKindKeyValueExpr,
		Name:     "KeyValueExpr",
	},
	NodeKindThisExpr: {
		NodeKind: NodeKindThisExpr,
		Name:     "ThisExpr",
	},
	NodeKindFuncType: {
		NodeKind: NodeKindFuncType,
		Name:     "FuncType",
	},
	NodeKindParamTypeList: {
		NodeKind: NodeKindParamTypeList,
		Name:     "ParamTypeList",
	},
	NodeKindFuncLit: {
		NodeKind: NodeKindFuncLit,
		Name:     "FuncLit",
	},
	NodeKindPointerType: {
		NodeKind: NodeKindPointerType,
		Name:     "PointerType",
	},
	NodeKindNewExpr: {
		NodeKind: NodeKindNewExpr,
		Name:     "NewExpr",
	},
	NodeKindDeleteStmt: {
		NodeKind: NodeKindDeleteStmt,
		Name:     "DeleteStmt",
	},
	NodeKindSliceExpr: {
		NodeKind: NodeKindSliceExpr,
		Name:     "SliceExpr",
	},
	NodeKindExternFuncDecl: {
		NodeKind: NodeKindExternFuncDecl,
		Name:     "ExternFuncDecl",
	},
	NodeKindMultiReturnType: {
		NodeKind: NodeKindMultiReturnType,
		Name:     "MultiReturnType",
	},
	NodeKindMultiValueExpr: {
		NodeKind: NodeKindMultiValueExpr,
		Name:     "MultiValueExpr",
	},
	NodeKindMultiShortVarDecl: {
		NodeKind: NodeKindMultiShortVarDecl,
		Name:     "MultiShortVarDecl",
	},
	NodeKindMultiAssignStmt: {
		NodeKind: NodeKindMultiAssignStmt,
		Name:     "MultiAssignStmt",
	},
}

var nodeKindValues = []NodeKind{
	NodeKindFile,
	NodeKindBad,
	NodeKindImportDecl,
	NodeKindVarDecl,
	NodeKindShortVarDecl,
	NodeKindFuncDecl,
	NodeKindParamList,
	NodeKindParam,
	NodeKindStructDecl,
	NodeKindField,
	NodeKindConstructorDecl,
	NodeKindDestructorDecl,
	NodeKindBlock,
	NodeKindExprStmt,
	NodeKindReturnStmt,
	NodeKindBreakStmt,
	NodeKindContinueStmt,
	NodeKindIfStmt,
	NodeKindForStmt,
	NodeKindAssignStmt,
	NodeKindIncDecStmt,
	NodeKindIdent,
	NodeKindNumberLit,
	NodeKindStringLit,
	NodeKindBoolLit,
	NodeKindBinaryExpr,
	NodeKindUnaryExpr,
	NodeKindCallExpr,
	NodeKindParenExpr,
	NodeKindIndexExpr,
	NodeKindMemberExpr,
	NodeKindArrayType,
	NodeKindCompositeLit,
	NodeKindKeyValueExpr,
	NodeKindThisExpr,
	NodeKindFuncType,
	NodeKindParamTypeList,
	NodeKindFuncLit,
	NodeKindPointerType,
	NodeKindNewExpr,
	NodeKindDeleteStmt,
	NodeKindSliceExpr,
	NodeKindExternFuncDecl,
	NodeKindMultiReturnType,
	NodeKindMultiValueExpr,
	NodeKindMultiShortVarDecl,
	NodeKindMultiAssignStmt,
}

var nodeKindByName = map[string]NodeKind{
	"file":              NodeKindFile,
	"bad":               NodeKindBad,
	"importdecl":        NodeKindImportDecl,
	"vardecl":           NodeKindVarDecl,
	"shortvardecl":      NodeKindShortVarDecl,
	"funcdecl":          NodeKindFuncDecl,
	"paramlist":         NodeKindParamList,
	"param":             NodeKindParam,
	"structdecl":        NodeKindStructDecl,
	"field":             NodeKindField,
	"constructordecl":   NodeKindConstructorDecl,
	"destructordecl":    NodeKindDestructorDecl,
	"block":             NodeKindBlock,
	"exprstmt":          NodeKindExprStmt,
	"returnstmt":        NodeKindReturnStmt,
	"breakstmt":         NodeKindBreakStmt,
	"continuestmt":      NodeKindContinueStmt,
	"ifstmt":            NodeKindIfStmt,
	"forstmt":           NodeKindForStmt,
	"assignstmt":        NodeKindAssignStmt,
	"incdecstmt":        NodeKindIncDecStmt,
	"ident":             NodeKindIdent,
	"numberlit":         NodeKindNumberLit,
	"stringlit":         NodeKindStringLit,
	"boollit":           NodeKindBoolLit,
	"binaryexpr":        NodeKindBinaryExpr,
	"unaryexpr":         NodeKindUnaryExpr,
	"callexpr":          NodeKindCallExpr,
	"parenexpr":         NodeKindParenExpr,
	"indexexpr":         NodeKindIndexExpr,
	"memberexpr":        NodeKindMemberExpr,
	"arraytype":         NodeKindArrayType,
	"compositelit":      NodeKindCompositeLit,
	"keyvalueexpr":      NodeKindKeyValueExpr,
	"thisexpr":          NodeKindThisExpr,
	"functype":          NodeKindFuncType,
	"paramtypelist":     NodeKindParamTypeList,
	"funclit":           NodeKindFuncLit,
	"pointertype":       NodeKindPointerType,
	"newexpr":           NodeKindNewExpr,
	"deletestmt":        NodeKindDeleteStmt,
	"sliceexpr":         NodeKindSliceExpr,
	"externfuncdecl":    NodeKindExternFuncDecl,
	"multireturntype":   NodeKindMultiReturnType,
	"multivalueexpr":    NodeKindMultiValueExpr,
	"multishortvardecl": NodeKindMultiShortVarDecl,
	"multiassignstmt":   NodeKindMultiAssignStmt,
}

// Values returns every declared value in declaration order.
func (c NodeKindContainer) Values() []NodeKind {
	out := make([]NodeKind, len(nodeKindValues))
	copy(out, nodeKindValues)
	return out
}

// Infos returns every declared value's metadata in declaration order.
func (c NodeKindContainer) Infos() []NodeKindInfo {
	out := make([]NodeKindInfo, len(nodeKindValues))
	for i, v := range nodeKindValues {
		out[i] = nodeKindInfos[v]
	}
	return out
}

// Len returns the number of declared values.
func (c NodeKindContainer) Len() int {
	return len(nodeKindValues)
}

// All iterates every declared value in declaration order.
func (c NodeKindContainer) All() iter.Seq[NodeKind] {
	return func(yield func(NodeKind) bool) {
		for _, v := range nodeKindValues {
			if !yield(v) {
				return
			}
		}
	}
}

// FromWire converts a raw wire value, reporting whether it is declared.
func (c NodeKindContainer) FromWire(w int) (NodeKind, bool) {
	v := NodeKind(w)
	_, ok := nodeKindInfos[v]
	return v, ok
}

// FromWireUnsafe converts a raw wire value, assuming it's declared.
func (c NodeKindContainer) FromWireUnsafe(w int) NodeKind {
	return NodeKind(w)
}

// Parse resolves a value by name, case-insensitively.
func (c NodeKindContainer) Parse(s string) (NodeKind, error) {
	if v, ok := nodeKindByName[strings.ToLower(strings.TrimSpace(s))]; ok {
		return v, nil
	}
	var zero NodeKind
	return zero, fmt.Errorf("unknown NodeKind: %q", s)
}

// TryGetInfo returns the metadata for v, and whether v is a declared value.
func (v NodeKind) TryGetInfo() (NodeKindInfo, bool) {
	i, ok := nodeKindInfos[v]
	return i, ok
}

// Info returns the metadata for v, and whether v is a declared value.
func (v NodeKind) Info() NodeKindInfo {
	return nodeKindInfos[v]
}

func (v NodeKind) Valid() bool {
	_, ok := nodeKindInfos[v]
	return ok
}

func (v NodeKind) Wire() int {
	return int(v)
}

func (v NodeKind) Name() string {
	return nodeKindInfos[v].Name
}

func (v NodeKind) String() string {
	if i, ok := nodeKindInfos[v]; ok {
		return i.Name
	}
	return fmt.Sprintf("NodeKind(%d)", int(v))
}
