package main

import (
	"bytes"
	"fmt"
	"go/types"
	"slices"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

// renderTS produces the generated TypeScript source for one enum spec: a values
// object, a derived union type, per-member metadata, and lookup tables that
// mirror the Go container.
func renderTS(s *spec, fields []field, entries []entry, srcName, tsOutAbs string) ([]byte, error) {
	var b bytes.Buffer
	p := func(format string, a ...any) { fmt.Fprintf(&b, format+"\n", a...) }

	members := liveEntries(entries)

	for _, f := range fields {
		if f.Type.strct != nil {
			return nil, fmt.Errorf("column %q has struct type %s, which is not supported in TypeScript output", f.Key, f.Type.elem)
		}
	}

	imports, err := tsImports(s, fields, members, tsOutAbs)
	if err != nil {
		return nil, err
	}

	T := pascal(s.Type)
	infoT := T + "Info"
	contV := *s.Container

	p("// Code generated by enumgen from %s. DO NOT EDIT.", srcName)
	p("")
	for _, im := range imports {
		if im.valueUsed {
			p("import { %s, type %s } from %q;", im.container, im.typ, im.module)
		} else {
			p("import type { %s } from %q;", im.typ, im.module)
		}
	}
	if len(imports) > 0 {
		p("")
	}

	p("export const %s = {", contV)
	for _, e := range members {
		p("  %s: %s,", s.memberIdent(e.Name), wireLit(s, e.Wire))
	}
	p("} as const;")
	p("")

	p("export type %s = (typeof %s)[keyof typeof %s];", T, contV, contV)
	p("")

	sentinels := sentinelEntries(entries)
	if len(sentinels) > 0 {
		p("// Const-only boundaries, excluded from the tables below.")
		for _, e := range sentinels {
			p("export const %s%s = %s;", T, s.memberIdent(e.Name), wireLit(s, e.Wire))
		}
		p("")
	}

	// A metadata column is optional in TS when any member omits it: unlike Go,
	// which must fall back to a zero value, TS models "absent" as an undefined
	// property rather than an empty string / empty array.
	optional := optionalFields(fields, members)

	p("export interface %s {", infoT)
	p("  value: %s;", T)
	p("  name: string;")
	for _, f := range fields {
		mark := ""
		if optional[f.Key] {
			mark = "?"
		}
		p("  %s%s: %s;", camel(f.Key), mark, f.Type.tsType())
	}
	p("}")
	p("")

	p("export const %sInfos: Record<%s, %s> = {", T, T, infoT)
	for _, e := range members {
		p("  [%s.%s]: {", contV, s.memberIdent(e.Name))
		p("    value: %s.%s,", contV, s.memberIdent(e.Name))
		p("    name: %q,", e.Name)
		for _, f := range fields {
			n := e.Nodes[f.Key]
			if n == nil || n.Tag == "!!null" {
				continue // absent: leave the optional property undefined
			}
			v, err := tsValue(f.Type, n)
			if err != nil {
				return nil, fmt.Errorf("%s.%s: %w", e.Name, f.Key, err)
			}
			p("    %s: %s,", camel(f.Key), v)
		}
		p("  },")
	}
	p("} as const;")
	p("")

	p("export const %sValues: readonly %s[] = [", T, T)
	for _, e := range members {
		p("  %s.%s,", contV, s.memberIdent(e.Name))
	}
	p("] as const;")
	p("")

	p("export const %sByName = {", T)
	for _, e := range members {
		p("  %q: %s.%s,", e.Name, contV, s.memberIdent(e.Name))
	}
	p("} as const;")
	p("")

	piped := ""
	for _, e := range members {
		piped += fmt.Sprintf("%q | ", e.Name)
	}

	p("export type %sNames = keyof (typeof %sByName)", T, T)
	p("")
	/*piped := ""
	for _, e := range members {
		piped += fmt.Sprintf("%q | ", e.Name)
	}

	p("export type %sNames = %s", T, piped[:len(piped)-3]) // trim trailing " | "
	p("")*/

	lower := camel(T) + "ByLowerName"
	p("const %s: Record<string, %s> = {};", lower, T)
	p("for (const [k, v] of Object.entries(%sByName)) {", T)
	p("  %s[k.toLowerCase()] = v;", lower)
	p("}")
	p("")
	p("// parse%s resolves a member by name, case-insensitively, mirroring the Go", T)
	p("// Parse method. Returns undefined when the name is unknown.")
	p("export function parse%s(name: string): %s | undefined {", T, T)
	p("  return %s[name.trim().toLowerCase()];", lower)
	p("}")

	iters, err := iteratorFields(s, fields)
	if err != nil {
		return nil, err
	}
	for _, f := range iters {
		ret := f.Type.tsType()
		if optional[f.Key] {
			ret += " | undefined"
		}
		p("")
		p("export function* iter%s(): Generator<%s> {", f.GoName, ret)
		p("  for (const v of %sValues) {", T)
		p("    yield %sInfos[v].%s;", T, camel(f.Key))
		p("  }")
		p("}")
	}

	return b.Bytes(), nil
}

// optionalFields reports, per metadata column, whether at least one member
// omits it (a nil or null node), making it an optional TS property.
func optionalFields(fields []field, members []entry) map[string]bool {
	opt := map[string]bool{}
	for _, f := range fields {
		for _, e := range members {
			if n := e.Nodes[f.Key]; n == nil || n.Tag == "!!null" {
				opt[f.Key] = true
				break
			}
		}
	}
	return opt
}

func sentinelEntries(entries []entry) []entry {
	var out []entry
	for _, e := range entries {
		if e.Sentinel {
			out = append(out, e)
		}
	}
	return out
}

// tsImport is one generated import line for a cross-file enum reference.
type tsImport struct {
	container string
	typ       string
	module    string
	valueUsed bool // whether any emitted value references the container
}

// tsImports gathers the imports needed for references to other enums' TS files,
// in a stable order. A reference to the same enum (self-reference) needs none.
func tsImports(s *spec, fields []field, members []entry, tsOutAbs string) ([]*tsImport, error) {
	byType := map[string]*tsImport{}
	var order []string
	for _, f := range fields {
		r := f.Type.ref
		if r == nil || r.spec == s {
			continue
		}
		im, ok := byType[r.spec.Type]
		if !ok {
			module, err := r.tsImportSpec(tsOutAbs)
			if err != nil {
				return nil, err
			}
			im = &tsImport{container: r.container, typ: r.spec.Type, module: module}
			byType[r.spec.Type] = im
			order = append(order, r.spec.Type)
		}
		if !im.valueUsed && fieldReferencesValue(f, members) {
			im.valueUsed = true
		}
	}
	slices.Sort(order)
	out := make([]*tsImport, 0, len(order))
	for _, k := range order {
		out = append(out, byType[k])
	}
	return out, nil
}

// fieldReferencesValue reports whether any member emits a value for the column
// (a present scalar, or a non-empty slice) — i.e. whether the container is used.
func fieldReferencesValue(f field, members []entry) bool {
	for _, e := range members {
		n := e.Nodes[f.Key]
		if n == nil || n.Tag == "!!null" {
			continue
		}
		if f.Type.slice && len(n.Content) == 0 {
			continue
		}
		return true
	}
	return false
}

// tsValue renders a present field value as a TypeScript literal of its resolved
// type. Absent nodes are omitted by the caller. Enum references resolve to the
// referenced container's accessor (e.g. StatIds.FishingSpeed), whether the
// container is local (self-reference) or imported (cross-file).
func tsValue(t ftype, n *yaml.Node) (string, error) {
	if t.slice {
		parts := make([]string, 0, len(n.Content))
		for _, c := range n.Content {
			v, err := tsScalar(t, c)
			if err != nil {
				return "", err
			}
			parts = append(parts, v)
		}
		return "[" + strings.Join(parts, ", ") + "]", nil
	}
	return tsScalar(t, n)
}

func tsScalar(t ftype, n *yaml.Node) (string, error) {
	if t.ref == nil {
		return tsBasicLit(t.elem, n), nil
	}
	if !t.ref.has(n.Value) {
		return "", fmt.Errorf("%q is not a member of %s", n.Value, t.ref.spec.Type)
	}
	return t.ref.tsRef(n.Value), nil
}

func tsBasicLit(elem string, n *yaml.Node) string {
	switch {
	case elem == "bool":
		return n.Value
	case basicInfo(elem)&(types.IsInteger|types.IsFloat) != 0:
		return n.Value
	default:
		return strconv.Quote(n.Value)
	}
}
