package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/types"
	"slices"
	"strings"
	"unicode"

	"gopkg.in/yaml.v3"
)

// renderKotlin produces a value-class wire wrapper with companion members,
// metadata, and lookup helpers.
func renderKotlin(s *spec, fields []field, entries []entry, srcName string) ([]byte, error) {
	var b bytes.Buffer
	p := func(format string, a ...any) {
		fmt.Fprintf(&b, format+"\n", a...)
	}

	members := liveEntries(entries)
	for _, f := range fields {
		if f.Type.strct != nil {
			return nil, fmt.Errorf(
				"column %q has struct type %s, which is not supported in Kotlin output",
				f.Key,
				f.Type.elem,
			)
		}
	}

	T := pascal(s.Type)
	infoT := T + "Info"
	wireT := kotlinBasicType(s.Underlying)
	optional := optionalFields(fields, members)
	packageName, err := kotlinPackageName(s.kotlinPackage())
	if err != nil {
		return nil, err
	}

	p("// Code generated by enumgen from %s. DO NOT EDIT.", srcName)
	p("")
	p("package %s", packageName)
	p("")

	imports, err := kotlinImports(s, fields)
	if err != nil {
		return nil, err
	}
	for _, im := range imports {
		p("import %s", im)
	}
	if len(imports) > 0 {
		p("")
	}

	p("@JvmInline")
	p("public value class %s(public val wire: %s) {", T, wireT)
	p("    public companion object {")
	for _, e := range members {
		p(
			"        public val %s: %s = %s(%s)",
			kotlinIdent(s.memberIdent(e.Name)),
			T,
			T,
			kotlinBasicLit(s.Underlying, scalarNode(e.Wire, s.stringUnderlying())),
		)
	}
	if len(members) > 0 {
		p("")
	}
	p("        public val entries: List<%s> = listOf(", T)
	for _, e := range members {
		p("            %s,", kotlinIdent(s.memberIdent(e.Name)))
	}
	p("        )")
	p("")
	p("        public val byName: Map<String, %s> = mapOf(", T)
	for _, e := range members {
		p("            %s to %s,", kotlinString(e.Name), kotlinIdent(s.memberIdent(e.Name)))
	}
	p("        )")
	p("")
	p("        private val byWire: Map<%s, %s> = entries.associateBy(%s::wire)", wireT, T, T)
	p("        private val byLowerName: Map<String, %s> =", T)
	p("            byName.mapKeys { (name, _) -> name.lowercase() }")
	p("")
	p("        public fun fromWire(wire: %s): %s? = byWire[wire]", wireT, T)
	p("")
	p("        public fun parse(name: String): %s? =", T)
	p("            byLowerName[name.trim().lowercase()]")
	p("    }")
	p("}")
	p("")

	sentinels := sentinelEntries(entries)
	aliases := aliasEntries(entries)
	for _, e := range sentinels {
		p(
			"public val %s%s: %s = %s(%s)",
			T,
			kotlinIdent(s.memberIdent(e.Name)),
			T,
			T,
			kotlinBasicLit(s.Underlying, scalarNode(e.Wire, s.stringUnderlying())),
		)
	}
	for _, e := range aliases {
		p(
			"public val %s%s: %s = %s.%s",
			T,
			kotlinIdent(s.memberIdent(e.Name)),
			T,
			T,
			kotlinIdent(s.memberIdent(e.Alias)),
		)
	}
	if len(sentinels)+len(aliases) > 0 {
		p("")
	}

	p("public data class %s(", infoT)
	p("    public val value: %s,", T)
	p("    public val name: String,")
	for _, f := range fields {
		typ := f.Type.ktType()
		if optional[f.Key] {
			typ += "?"
		}
		p("    public val %s: %s,", kotlinIdent(camel(f.Key)), typ)
	}
	p(")")
	p("")

	p("public val %sInfos: Map<%s, %s> = mapOf(", T, T, infoT)
	for _, e := range members {
		member := kotlinIdent(s.memberIdent(e.Name))
		p("    %s.%s to %s(", T, member, infoT)
		p("        value = %s.%s,", T, member)
		p("        name = %s,", kotlinString(e.Name))
		for _, f := range fields {
			n := e.Nodes[f.Key]
			value := "null"
			if n != nil && n.Tag != "!!null" {
				var err error
				value, err = kotlinValue(f.Type, n)
				if err != nil {
					return nil, fmt.Errorf("%s.%s: %w", e.Name, f.Key, err)
				}
			}
			p("        %s = %s,", kotlinIdent(camel(f.Key)), value)
		}
		p("    ),")
	}
	p(")")
	p("")
	p("public val %s.info: %s?", T, infoT)
	p("    get() = %sInfos[this]", T)

	iters, err := iteratorFields(s, fields)
	if err != nil {
		return nil, err
	}
	for _, f := range iters {
		typ := f.Type.ktType()
		if optional[f.Key] {
			typ += "?"
		}
		p("")
		p("public fun iter%s(): Sequence<%s> =", f.GoName, typ)
		p("    %s.entries.asSequence().map { %sInfos.getValue(it).%s }", T, T, kotlinIdent(camel(f.Key)))
	}

	return b.Bytes(), nil
}

func kotlinImports(s *spec, fields []field) ([]string, error) {
	imports := make([]string, 0)
	seen := map[string]bool{}
	for _, f := range fields {
		r := f.Type.ref
		if r == nil || r.spec == s || r.ktPackage == s.kotlinPackage() {
			continue
		}
		pkg, err := kotlinPackageName(r.ktPackage)
		if err != nil {
			return nil, fmt.Errorf("referenced enum %s: %w", r.spec.Type, err)
		}
		im := pkg + "." + pascal(r.spec.Type)
		if !seen[im] {
			seen[im] = true
			imports = append(imports, im)
		}
	}
	slices.Sort(imports)
	return imports, nil
}

func kotlinValue(t ftype, n *yaml.Node) (string, error) {
	if t.slice {
		parts := make([]string, 0, len(n.Content))
		for _, child := range n.Content {
			value, err := kotlinScalar(t, child)
			if err != nil {
				return "", err
			}
			parts = append(parts, value)
		}
		return "listOf(" + strings.Join(parts, ", ") + ")", nil
	}
	return kotlinScalar(t, n)
}

func kotlinScalar(t ftype, n *yaml.Node) (string, error) {
	if t.ref == nil {
		return kotlinBasicLit(t.elem, n), nil
	}
	if !t.ref.has(n.Value) {
		return "", fmt.Errorf("%q is not a member of %s", n.Value, t.ref.spec.Type)
	}
	return pascal(t.ref.spec.Type) + "." + kotlinIdent(t.ref.spec.memberIdent(n.Value)), nil
}

func kotlinBasicType(goType string) string {
	switch goType {
	case "bool":
		return "Boolean"
	case "string":
		return "String"
	case "int8":
		return "Byte"
	case "int16":
		return "Short"
	case "int",
		"int32",
		"rune":
		return "Int"
	case "int64":
		return "Long"
	case "byte",
		"uint8":
		return "UByte"
	case "uint16":
		return "UShort"
	case "uint",
		"uint32":
		return "UInt"
	case "uint64",
		"uintptr":
		return "ULong"
	case "float32":
		return "Float"
	case "float64":
		return "Double"
	default:
		return "String"
	}
}

func kotlinBasicLit(goType string, n *yaml.Node) string {
	switch {
	case goType == "string":
		return kotlinString(n.Value)
	case goType == "bool":
		return n.Value
	case goType == "float32":
		return kotlinFloat(n.Value) + "f"
	case goType == "float64":
		return kotlinFloat(n.Value)
	case basicInfo(goType)&types.IsUnsigned != 0:
		if goType == "uint64" || goType == "uintptr" {
			return n.Value + "uL"
		}
		return n.Value + "u"
	case goType == "int64":
		return n.Value + "L"
	default:
		return n.Value
	}
}

func kotlinFloat(value string) string {
	if strings.ContainsAny(value, ".eE") {
		return value
	}
	return value + ".0"
}

func kotlinString(value string) string {
	encoded, _ := json.Marshal(value)
	return strings.ReplaceAll(string(encoded), "$", `\$`)
}

func scalarNode(value string, stringValue bool) *yaml.Node {
	tag := "!!int"
	if stringValue {
		tag = "!!str"
	}
	return &yaml.Node{
		Kind:  yaml.ScalarNode,
		Tag:   tag,
		Value: value,
	}
}

func kotlinIdent(ident string) string {
	if kotlinKeywords[ident] {
		return "`" + ident + "`"
	}
	return ident
}

func kotlinPackageName(name string) (string, error) {
	parts := strings.Split(name, ".")
	for i, part := range parts {
		if !validKotlinIdentifier(part) {
			return "", fmt.Errorf("invalid Kotlin package segment %q in %q", part, name)
		}
		parts[i] = kotlinIdent(part)
	}
	return strings.Join(parts, "."), nil
}

func validKotlinIdentifier(ident string) bool {
	for i, r := range ident {
		if r != '_' && !unicode.IsLetter(r) && (i == 0 || !unicode.IsDigit(r)) {
			return false
		}
	}
	return ident != ""
}

var kotlinKeywords = map[string]bool{
	"as": true, "break": true, "class": true, "continue": true,
	"do": true, "else": true, "false": true, "for": true,
	"fun": true, "if": true, "in": true, "interface": true,
	"is": true, "null": true, "object": true, "package": true,
	"return": true, "super": true, "this": true, "throw": true,
	"true": true, "try": true, "typealias": true, "typeof": true,
	"val": true, "var": true, "when": true, "while": true,
}
