package main

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
)

// renderGo produces the generated Go source for one enum spec.
func renderGo(s *spec, fields []field, entries []entry, srcName string) ([]byte, error) {
	var b bytes.Buffer
	p := func(format string, a ...any) { fmt.Fprintf(&b, format+"\n", a...) }

	members := liveEntries(entries)

	T := s.Type
	exportedType := pascal(T)
	unexportedType := unexport(T)
	infoT := T + "Info"
	contT := exportedType + "Container"
	contV := *s.Container

	p("// Code generated by enumgen from %s. DO NOT EDIT.", srcName)
	p("")
	p("package %s", s.Package)
	p("")
	p("import (")
	p("\t%q", "fmt")
	p("\t%q", "iter")
	p("\t%q", "strings")
	p(")")
	p("")
	p("// %s is a %s-wide identifier. The zero-cost conversion %s(x) is", T, s.Underlying, T)
	p("// intentional: the underlying value is the wire value.")
	p("type %s %s", T, s.Underlying)
	p("")
	p("const (")
	for _, e := range entries {
		p("\t%s%s %s = %s", exportedType, s.memberIdent(e.Name), T, wireLit(s, e.Wire))
	}
	p(")")
	p("")

	// Container
	p("type %s struct {", contT)
	for _, e := range members {
		p("\t%s %s", s.memberIdent(e.Name), T)
	}
	p("}")
	p("")
	p("// %s is the entry point for the %s enum.", contV, T)
	p("var %s = %s{", contV, contT)
	for _, e := range members {
		p("\t%s: %s%s,", s.memberIdent(e.Name), exportedType, s.memberIdent(e.Name))
	}
	p("}")
	p("")

	// Info struct
	p("// %s is the static metadata attached to a %s.", infoT, T)
	p("type %s struct {", infoT)
	p("\t%s", T)
	p("\tName string")
	for _, f := range fields {
		p("\t%s %s", f.GoName, f.Type.goType())
	}
	p("}")
	p("")

	// Tables
	p("var %sInfos = map[%s]%s{", unexportedType, T, infoT)
	for _, e := range members {
		p("\t%s%s: {", exportedType, s.memberIdent(e.Name))
		p("\t\t%s: %s%s,", exportedType, exportedType, s.memberIdent(e.Name))
		p("\t\tName: %q,", e.Name)
		for _, f := range fields {
			v, emit, err := goValue(f.Type, e.Nodes[f.Key])
			if err != nil {
				return nil, fmt.Errorf("%s.%s: %w", e.Name, f.Key, err)
			}
			if emit {
				p("\t\t%s: %s,", f.GoName, v)
			}
		}
		p("\t},")
	}
	p("}")
	p("")

	p("var %sValues = []%s{", unexportedType, T)
	for _, e := range members {
		p("\t%s%s,", exportedType, s.memberIdent(e.Name))
	}
	p("}")
	p("")

	p("var %sByName = map[string]%s{", unexportedType, T)
	for _, e := range members {
		p("\t%q: %s%s,", strings.ToLower(e.Name), exportedType, s.memberIdent(e.Name))
	}
	p("}")
	p("")

	// Container methods
	p("// Values returns every declared value in declaration order.")
	p("func (c %s) Values() []%s {", contT, T)
	p("\tout := make([]%s, len(%sValues))", T, unexportedType)
	p("\tcopy(out, %sValues)", unexportedType)
	p("\treturn out")
	p("}")
	p("")

	p("// Infos returns every declared value's metadata in declaration order.")
	p("func (c %s) Infos() []%s {", contT, infoT)
	p("\tout := make([]%s, len(%sValues))", infoT, unexportedType)
	p("\tfor i, v := range %sValues {", unexportedType)
	p("\t\tout[i] = %sInfos[v]", unexportedType)
	p("\t}")
	p("\treturn out")
	p("}")
	p("")

	p("// Len returns the number of declared values.")
	p("func (c %s) Len() int {", contT)
	p("\treturn len(%sValues)", unexportedType)
	p("}")
	p("")

	p("// All iterates every declared value in declaration order.")
	p("func (c %s) All() iter.Seq[%s] {", contT, T)
	p("\treturn func(yield func(%s) bool) {", T)
	p("\t\tfor _, v := range %sValues {", unexportedType)
	p("\t\t\tif !yield(v) {")
	p("\t\t\t\treturn")
	p("\t\t\t}")
	p("\t\t}")
	p("\t}")
	p("}")
	p("")

	p("// FromWire converts a raw wire value, reporting whether it is declared.")
	p("func (c %s) FromWire(w %s) (%s, bool) {", contT, s.Underlying, T)
	p("\tv := %s(w)", T)
	p("\t_, ok := %sInfos[v]", unexportedType)
	p("\treturn v, ok")
	p("}")
	p("")

	p("// FromWireUnsafe converts a raw wire value, assuming it's declared.")
	p("func (c %s) FromWireUnsafe(w %s) %s {", contT, s.Underlying, T)
	p("\treturn %s(w)", T)
	p("}")
	p("")

	p("// Parse resolves a value by name, case-insensitively.")
	p("func (c %s) Parse(s string) (%s, error) {", contT, T)
	p("\tif v, ok := %sByName[strings.ToLower(strings.TrimSpace(s))]; ok {", unexportedType)
	p("\t\treturn v, nil")
	p("\t}")
	p("\tvar zero %s", T)
	p("\treturn zero, fmt.Errorf(%q, s)", "unknown "+T+": %q")
	p("}")
	p("")

	// Value methods
	p("// TryGetInfo returns the metadata for v, and whether v is a declared value.")
	p("func (v %s) TryGetInfo() (%s, bool) {", T, infoT)
	p("\ti, ok := %sInfos[v]", unexportedType)
	p("\treturn i, ok")
	p("}")
	p("")
	p("// Info returns the metadata for v, and whether v is a declared value.")
	p("func (v %s) Info() %s {", T, infoT)
	p("\treturn %sInfos[v]", unexportedType)
	p("}")
	p("")

	p("func (v %s) Valid() bool {", T)
	p("\t_, ok := %sInfos[v]", unexportedType)
	p("\treturn ok")
	p("}")
	p("")

	p("func (v %s) Wire() %s {", T, s.Underlying)
	p("\treturn %s(v)", s.Underlying)
	p("}")
	p("")

	p("func (v %s) Name() string {", T)
	p("\treturn %sInfos[v].Name", unexportedType)
	p("}")
	p("")

	p("func (v %s) String() string {", T)
	p("\tif i, ok := %sInfos[v]; ok {", unexportedType)
	p("\t\treturn i.Name")
	p("\t}")
	p("\treturn fmt.Sprintf(%q, %s(v))", T+"("+s.fmtVerb()+")", s.Underlying)
	p("}")
	p("")

	reserved := map[string]bool{"Name": true, "String": true, "Info": true, "TryGetInfo": true, "Valid": true, "Wire": true}
	for _, f := range fields {
		if reserved[f.GoName] {
			continue
		}
		p("func (v %s) %s() %s {", T, f.GoName, f.Type.goType())
		p("\treturn %sInfos[v].%s", unexportedType, f.GoName)
		p("}")
		p("")
	}

	iters, err := iteratorFields(s, fields)
	if err != nil {
		return nil, err
	}
	for _, f := range iters {
		ft := f.Type.goType()
		p("// Iter%s iterates each declared value's %s in declaration order.", f.GoName, f.GoName)
		p("func (c %s) Iter%s() iter.Seq[%s] {", contT, f.GoName, ft)
		p("\treturn func(yield func(%s) bool) {", ft)
		p("\t\tfor _, v := range %sValues {", unexportedType)
		p("\t\t\tif !yield(%sInfos[v].%s) {", unexportedType, f.GoName)
		p("\t\t\t\treturn")
		p("\t\t\t}")
		p("\t\t}")
		p("\t}")
		p("}")
		p("")
	}

	if s.MarshalText {
		p("func (v %s) MarshalText() ([]byte, error) {", T)
		p("\tif !v.Valid() {")
		p("\t\treturn nil, fmt.Errorf(%q, %s(v))", "invalid "+T+": "+s.fmtVerb(), s.Underlying)
		p("\t}")
		p("\treturn []byte(v.Name()), nil")
		p("}")
		p("")

		p("func (v *%s) UnmarshalText(b []byte) error {", T)
		p("\tp, err := %s.Parse(string(b))", contV)
		p("\tif err != nil {")
		p("\t\treturn err")
		p("\t}")
		p("\t*v = p")
		p("\treturn nil")
		p("}")
	}

	src, err := format.Source(b.Bytes())
	if err != nil {
		// dump the unformatted source so the failure is debuggable
		return nil, fmt.Errorf("gofmt: %w\n%s", err, b.String())
	}
	return src, nil
}
