package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/types"
	"slices"
	"strings"
	"unicode"

	"gopkg.in/yaml.v3"
)

// renderKotlin produces an enum class with per-entry metadata and wire/name
// lookup helpers.
func renderKotlin(s *spec, fields []field, entries []entry, srcName string) ([]byte, error) {
	var b bytes.Buffer
	p := func(format string, a ...any) {
		fmt.Fprintf(&b, format+"\n", a...)
	}

	members := liveEntries(entries)
	for _, f := range fields {
		if f.Type.strct != nil {
			return nil, fmt.Errorf(
				"column %q has struct type %s, which is not supported in Kotlin output",
				f.Key,
				f.Type.elem,
			)
		}
		switch camel(f.Key) {
		case "entries", "ordinal":
			return nil, fmt.Errorf(
				"column %q conflicts with Kotlin enum property %q",
				f.Key,
				camel(f.Key),
			)
		}
	}

	T := pascal(s.Type)
	constPrefix := s.constPrefix()
	wireT := kotlinBasicType(s.Underlying)
	optional := optionalFields(fields, members)
	aliases := aliasEntries(entries)
	visibility := s.kotlinVisibilityPrefix()
	memberVisibility := s.kotlinMemberVisibilityPrefix()
	packageName, err := kotlinPackageName(s.kotlinPackage())
	if err != nil {
		return nil, err
	}

	p("// Code generated by enumgen from %s. DO NOT EDIT.", srcName)
	p("")
	p("package %s", packageName)
	p("")

	imports, err := kotlinImports(s, fields)
	if err != nil {
		return nil, err
	}
	for _, im := range imports {
		p("import %s", im)
	}
	if len(imports) > 0 {
		p("")
	}

	p("%senum class %s(", visibility, T)
	p("    %sval wire: %s,", memberVisibility, wireT)
	for _, f := range fields {
		typ := f.Type.ktType()
		if optional[f.Key] {
			typ += "?"
		}
		p("    %sval %s: %s,", memberVisibility, kotlinIdent(camel(f.Key)), typ)
	}
	p(") {")
	for _, e := range members {
		args := []string{
			kotlinBasicLit(
				s.Underlying,
				scalarNode(e.Wire, s.stringUnderlying()),
			),
		}
		for _, f := range fields {
			n := e.Nodes[f.Key]
			value := "null"
			if n != nil && n.Tag != "!!null" {
				value, err = kotlinValue(f.Type, n)
				if err != nil {
					return nil, fmt.Errorf("%s.%s: %w", e.Name, f.Key, err)
				}
			}
			args = append(args, value)
		}
		p(
			"    %s(%s),",
			kotlinIdent(s.memberIdent(e.Name)),
			strings.Join(args, ", "),
		)
	}
	p("    ;")
	p("")
	p("    %scompanion object {", memberVisibility)
	p("        private val byWire: Map<%s, %s> = entries.associateBy(%s::wire)", wireT, T, T)
	p("        private val byLowerName: Map<String, %s> =", T)
	if len(aliases) == 0 {
		p("            entries.associateBy { it.name.lowercase() }")
	} else {
		p("            entries.associateBy { it.name.lowercase() } +")
		p("                mapOf(")
		for _, e := range aliases {
			p(
				"                    %s to %s.%s,",
				kotlinString(strings.ToLower(e.Name)),
				T,
				kotlinIdent(s.memberIdent(e.Alias)),
			)
		}
		p("                )")
	}
	p("")
	p("        %sfun fromWire(wire: %s): %s? = byWire[wire]", memberVisibility, wireT, T)
	p("")
	p("        %sfun parse(name: String): %s? =", memberVisibility, T)
	p("            byLowerName[name.trim().lowercase()]")
	p("    }")
	p("}")
	p("")

	sentinels := sentinelEntries(entries)
	for _, e := range sentinels {
		p(
			"%sval %s: %s = %s",
			visibility,
			kotlinPrefixedIdent(constPrefix, s.memberIdent(e.Name)),
			wireT,
			kotlinBasicLit(s.Underlying, scalarNode(e.Wire, s.stringUnderlying())),
		)
	}
	for _, e := range aliases {
		p(
			"%sval %s: %s = %s.%s",
			visibility,
			kotlinPrefixedIdent(constPrefix, s.memberIdent(e.Name)),
			T,
			T,
			kotlinIdent(s.memberIdent(e.Alias)),
		)
	}
	if len(sentinels)+len(aliases) > 0 {
		p("")
	}

	iters, err := iteratorFields(s, fields)
	if err != nil {
		return nil, err
	}
	for _, f := range iters {
		if !f.Type.slice && basicInfo(f.Type.elem)&types.IsBoolean != 0 {
			p("")
			p("%sfun iter%s(): Sequence<%s> =", visibility, f.GoName, T)
			p(
				"    %s.entries.asSequence().filter { it.%s == true }",
				T,
				kotlinIdent(camel(f.Key)),
			)
			continue
		}
		typ := f.Type.ktType()
		if optional[f.Key] {
			typ += "?"
		}
		p("")
		p("%sfun iter%s(): Sequence<%s> =", visibility, f.GoName, typ)
		p("    %s.entries.asSequence().map { it.%s }", T, kotlinIdent(camel(f.Key)))
	}

	return b.Bytes(), nil
}

func kotlinImports(s *spec, fields []field) ([]string, error) {
	imports := make([]string, 0)
	seen := map[string]bool{}
	for _, f := range fields {
		r := f.Type.ref
		if r == nil || r.spec == s || r.ktPackage == s.kotlinPackage() {
			continue
		}
		pkg, err := kotlinPackageName(r.ktPackage)
		if err != nil {
			return nil, fmt.Errorf("referenced enum %s: %w", r.spec.Type, err)
		}
		im := pkg + "." + pascal(r.spec.Type)
		if !seen[im] {
			seen[im] = true
			imports = append(imports, im)
		}
	}
	slices.Sort(imports)
	return imports, nil
}

func kotlinValue(t ftype, n *yaml.Node) (string, error) {
	if t.slice {
		parts := make([]string, 0, len(n.Content))
		for _, child := range n.Content {
			value, err := kotlinScalar(t, child)
			if err != nil {
				return "", err
			}
			parts = append(parts, value)
		}
		return "listOf(" + strings.Join(parts, ", ") + ")", nil
	}
	return kotlinScalar(t, n)
}

func kotlinScalar(t ftype, n *yaml.Node) (string, error) {
	if t.ref == nil {
		return kotlinBasicLit(t.elem, n), nil
	}
	if !t.ref.has(n.Value) {
		return "", fmt.Errorf("%q is not a member of %s", n.Value, t.ref.spec.Type)
	}
	return pascal(t.ref.spec.Type) + "." + kotlinIdent(t.ref.spec.memberIdent(n.Value)), nil
}

func kotlinBasicType(goType string) string {
	switch goType {
	case "bool":
		return "Boolean"
	case "string":
		return "String"
	case "int8":
		return "Byte"
	case "int16":
		return "Short"
	case "int",
		"int32",
		"rune":
		return "Int"
	case "int64":
		return "Long"
	case "byte",
		"uint8":
		return "UByte"
	case "uint16":
		return "UShort"
	case "uint",
		"uint32":
		return "UInt"
	case "uint64",
		"uintptr":
		return "ULong"
	case "float32":
		return "Float"
	case "float64":
		return "Double"
	default:
		return "String"
	}
}

func kotlinBasicLit(goType string, n *yaml.Node) string {
	switch {
	case goType == "string":
		return kotlinString(n.Value)
	case goType == "bool":
		return n.Value
	case goType == "float32":
		return kotlinFloat(n.Value) + "f"
	case goType == "float64":
		return kotlinFloat(n.Value)
	case basicInfo(goType)&types.IsUnsigned != 0:
		if goType == "uint64" || goType == "uintptr" {
			return n.Value + "uL"
		}
		return n.Value + "u"
	case goType == "int64":
		return n.Value + "L"
	default:
		return n.Value
	}
}

func kotlinFloat(value string) string {
	if strings.ContainsAny(value, ".eE") {
		return value
	}
	return value + ".0"
}

func kotlinString(value string) string {
	var b bytes.Buffer
	encoder := json.NewEncoder(&b)
	encoder.SetEscapeHTML(false)
	_ = encoder.Encode(value)
	encoded := strings.TrimSuffix(b.String(), "\n")
	return strings.ReplaceAll(encoded, "$", `\$`)
}

func scalarNode(value string, stringValue bool) *yaml.Node {
	tag := "!!int"
	if stringValue {
		tag = "!!str"
	}
	return &yaml.Node{
		Kind:  yaml.ScalarNode,
		Tag:   tag,
		Value: value,
	}
}

func kotlinIdent(ident string) string {
	if kotlinKeywords[ident] {
		return "`" + ident + "`"
	}
	return ident
}

func kotlinPrefixedIdent(prefix, member string) string {
	return kotlinIdent(prefix + member)
}

func kotlinPackageName(name string) (string, error) {
	parts := strings.Split(name, ".")
	for i, part := range parts {
		if !validKotlinIdentifier(part) {
			return "", fmt.Errorf("invalid Kotlin package segment %q in %q", part, name)
		}
		parts[i] = kotlinIdent(part)
	}
	return strings.Join(parts, "."), nil
}

func validKotlinIdentifier(ident string) bool {
	for i, r := range ident {
		if r != '_' && !unicode.IsLetter(r) && (i == 0 || !unicode.IsDigit(r)) {
			return false
		}
	}
	return ident != ""
}

var kotlinKeywords = map[string]bool{
	"as": true, "break": true, "class": true, "continue": true,
	"do": true, "else": true, "false": true, "for": true,
	"fun": true, "if": true, "in": true, "interface": true,
	"is": true, "null": true, "object": true, "package": true,
	"return": true, "super": true, "this": true, "throw": true,
	"true": true, "try": true, "typealias": true, "typeof": true,
	"val": true, "var": true, "when": true, "while": true,
}
