// Code generated by enumgen from type_kind.yml. DO NOT EDIT.

package sema

import (
	"fmt"
	"iter"
	"strings"
)

// TypeKind is a int-wide identifier. The zero-cost conversion TypeKind(x) is
// intentional: the underlying value is the wire value.
type TypeKind int

const (
	TypeInvalid      TypeKind = 0
	TypeVoid         TypeKind = 1
	TypeI8           TypeKind = 2
	TypeI16          TypeKind = 3
	TypeI32          TypeKind = 4
	TypeI64          TypeKind = 5
	TypeU8           TypeKind = 6
	TypeU16          TypeKind = 7
	TypeU32          TypeKind = 8
	TypeU64          TypeKind = 9
	TypeF32          TypeKind = 10
	TypeF64          TypeKind = 11
	TypeString       TypeKind = 12
	TypeCString      TypeKind = 13
	TypeBool         TypeKind = 14
	TypeStruct       TypeKind = 15
	TypeArray        TypeKind = 16
	TypeFunc         TypeKind = 17
	TypeCFunc        TypeKind = 18
	TypePointer      TypeKind = 19
	TypeMap          TypeKind = 20
	TypeEnum         TypeKind = 21
	TypeUntypedInt   TypeKind = 22
	TypeUntypedFloat TypeKind = 23
	TypeUntypedNil   TypeKind = 24
	TypeMultiReturn  TypeKind = 25
	TypeGenerator    TypeKind = 26
	TypeCoroutine    TypeKind = 27
	TypeInt                   = TypeI32
)

type TypeKindContainer struct {
	Invalid      TypeKind
	Void         TypeKind
	I8           TypeKind
	I16          TypeKind
	I32          TypeKind
	I64          TypeKind
	U8           TypeKind
	U16          TypeKind
	U32          TypeKind
	U64          TypeKind
	F32          TypeKind
	F64          TypeKind
	String       TypeKind
	CString      TypeKind
	Bool         TypeKind
	Struct       TypeKind
	Array        TypeKind
	Func         TypeKind
	CFunc        TypeKind
	Pointer      TypeKind
	Map          TypeKind
	Enum         TypeKind
	UntypedInt   TypeKind
	UntypedFloat TypeKind
	UntypedNil   TypeKind
	MultiReturn  TypeKind
	Generator    TypeKind
	Coroutine    TypeKind
}

// TypeKinds is the entry point for the TypeKind enum.
var TypeKinds = TypeKindContainer{
	Invalid:      TypeInvalid,
	Void:         TypeVoid,
	I8:           TypeI8,
	I16:          TypeI16,
	I32:          TypeI32,
	I64:          TypeI64,
	U8:           TypeU8,
	U16:          TypeU16,
	U32:          TypeU32,
	U64:          TypeU64,
	F32:          TypeF32,
	F64:          TypeF64,
	String:       TypeString,
	CString:      TypeCString,
	Bool:         TypeBool,
	Struct:       TypeStruct,
	Array:        TypeArray,
	Func:         TypeFunc,
	CFunc:        TypeCFunc,
	Pointer:      TypePointer,
	Map:          TypeMap,
	Enum:         TypeEnum,
	UntypedInt:   TypeUntypedInt,
	UntypedFloat: TypeUntypedFloat,
	UntypedNil:   TypeUntypedNil,
	MultiReturn:  TypeMultiReturn,
	Generator:    TypeGenerator,
	Coroutine:    TypeCoroutine,
}

// TypeKindInfo is the static metadata attached to a TypeKind.
type TypeKindInfo struct {
	TypeKind
	Name      string
	Display   string
	Bits      int
	Integer   bool
	Primitive bool
	Unsigned  bool
	Float     bool
	Untyped   bool
}

var typeKindInfos = [...]TypeKindInfo{
	TypeInvalid: {
		TypeKind:  TypeInvalid,
		Name:      "Invalid",
		Display:   "<invalid>",
		Bits:      0,
		Integer:   false,
		Primitive: false,
		Unsigned:  false,
		Float:     false,
		Untyped:   false,
	},
	TypeVoid: {
		TypeKind:  TypeVoid,
		Name:      "Void",
		Display:   "void",
		Bits:      0,
		Integer:   false,
		Primitive: false,
		Unsigned:  false,
		Float:     false,
		Untyped:   false,
	},
	TypeI8: {
		TypeKind:  TypeI8,
		Name:      "I8",
		Display:   "i8",
		Bits:      8,
		Integer:   true,
		Primitive: true,
		Unsigned:  false,
		Float:     false,
		Untyped:   false,
	},
	TypeI16: {
		TypeKind:  TypeI16,
		Name:      "I16",
		Display:   "i16",
		Bits:      16,
		Integer:   true,
		Primitive: true,
		Unsigned:  false,
		Float:     false,
		Untyped:   false,
	},
	TypeI32: {
		TypeKind:  TypeI32,
		Name:      "I32",
		Display:   "int",
		Bits:      32,
		Integer:   true,
		Primitive: true,
		Unsigned:  false,
		Float:     false,
		Untyped:   false,
	},
	TypeI64: {
		TypeKind:  TypeI64,
		Name:      "I64",
		Display:   "i64",
		Bits:      64,
		Integer:   true,
		Primitive: true,
		Unsigned:  false,
		Float:     false,
		Untyped:   false,
	},
	TypeU8: {
		TypeKind:  TypeU8,
		Name:      "U8",
		Display:   "u8",
		Bits:      8,
		Integer:   true,
		Primitive: true,
		Unsigned:  true,
		Float:     false,
		Untyped:   false,
	},
	TypeU16: {
		TypeKind:  TypeU16,
		Name:      "U16",
		Display:   "u16",
		Bits:      16,
		Integer:   true,
		Primitive: true,
		Unsigned:  true,
		Float:     false,
		Untyped:   false,
	},
	TypeU32: {
		TypeKind:  TypeU32,
		Name:      "U32",
		Display:   "u32",
		Bits:      32,
		Integer:   true,
		Primitive: true,
		Unsigned:  true,
		Float:     false,
		Untyped:   false,
	},
	TypeU64: {
		TypeKind:  TypeU64,
		Name:      "U64",
		Display:   "u64",
		Bits:      64,
		Integer:   true,
		Primitive: true,
		Unsigned:  true,
		Float:     false,
		Untyped:   false,
	},
	TypeF32: {
		TypeKind:  TypeF32,
		Name:      "F32",
		Display:   "f32",
		Bits:      32,
		Integer:   false,
		Primitive: true,
		Unsigned:  false,
		Float:     true,
		Untyped:   false,
	},
	TypeF64: {
		TypeKind:  TypeF64,
		Name:      "F64",
		Display:   "f64",
		Bits:      64,
		Integer:   false,
		Primitive: true,
		Unsigned:  false,
		Float:     true,
		Untyped:   false,
	},
	TypeString: {
		TypeKind:  TypeString,
		Name:      "String",
		Display:   "string",
		Bits:      0,
		Integer:   false,
		Primitive: true,
		Unsigned:  false,
		Float:     false,
		Untyped:   false,
	},
	TypeCString: {
		TypeKind:  TypeCString,
		Name:      "CString",
		Display:   "cstring",
		Bits:      0,
		Integer:   false,
		Primitive: true,
		Unsigned:  false,
		Float:     false,
		Untyped:   false,
	},
	TypeBool: {
		TypeKind:  TypeBool,
		Name:      "Bool",
		Display:   "bool",
		Bits:      0,
		Integer:   false,
		Primitive: true,
		Unsigned:  false,
		Float:     false,
		Untyped:   false,
	},
	TypeStruct: {
		TypeKind:  TypeStruct,
		Name:      "Struct",
		Display:   "",
		Bits:      0,
		Integer:   false,
		Primitive: false,
		Unsigned:  false,
		Float:     false,
		Untyped:   false,
	},
	TypeArray: {
		TypeKind:  TypeArray,
		Name:      "Array",
		Display:   "",
		Bits:      0,
		Integer:   false,
		Primitive: false,
		Unsigned:  false,
		Float:     false,
		Untyped:   false,
	},
	TypeFunc: {
		TypeKind:  TypeFunc,
		Name:      "Func",
		Display:   "",
		Bits:      0,
		Integer:   false,
		Primitive: false,
		Unsigned:  false,
		Float:     false,
		Untyped:   false,
	},
	TypeCFunc: {
		TypeKind:  TypeCFunc,
		Name:      "CFunc",
		Display:   "",
		Bits:      0,
		Integer:   false,
		Primitive: false,
		Unsigned:  false,
		Float:     false,
		Untyped:   false,
	},
	TypePointer: {
		TypeKind:  TypePointer,
		Name:      "Pointer",
		Display:   "",
		Bits:      0,
		Integer:   false,
		Primitive: false,
		Unsigned:  false,
		Float:     false,
		Untyped:   false,
	},
	TypeMap: {
		TypeKind:  TypeMap,
		Name:      "Map",
		Display:   "",
		Bits:      0,
		Integer:   false,
		Primitive: false,
		Unsigned:  false,
		Float:     false,
		Untyped:   false,
	},
	TypeEnum: {
		TypeKind:  TypeEnum,
		Name:      "Enum",
		Display:   "",
		Bits:      0,
		Integer:   false,
		Primitive: false,
		Unsigned:  false,
		Float:     false,
		Untyped:   false,
	},
	TypeUntypedInt: {
		TypeKind:  TypeUntypedInt,
		Name:      "UntypedInt",
		Display:   "untyped int",
		Bits:      0,
		Integer:   true,
		Primitive: false,
		Unsigned:  false,
		Float:     false,
		Untyped:   true,
	},
	TypeUntypedFloat: {
		TypeKind:  TypeUntypedFloat,
		Name:      "UntypedFloat",
		Display:   "untyped float",
		Bits:      0,
		Integer:   false,
		Primitive: false,
		Unsigned:  false,
		Float:     true,
		Untyped:   true,
	},
	TypeUntypedNil: {
		TypeKind:  TypeUntypedNil,
		Name:      "UntypedNil",
		Display:   "nil",
		Bits:      0,
		Integer:   false,
		Primitive: false,
		Unsigned:  false,
		Float:     false,
		Untyped:   false,
	},
	TypeMultiReturn: {
		TypeKind:  TypeMultiReturn,
		Name:      "MultiReturn",
		Display:   "",
		Bits:      0,
		Integer:   false,
		Primitive: false,
		Unsigned:  false,
		Float:     false,
		Untyped:   false,
	},
	TypeGenerator: {
		TypeKind:  TypeGenerator,
		Name:      "Generator",
		Display:   "",
		Bits:      0,
		Integer:   false,
		Primitive: false,
		Unsigned:  false,
		Float:     false,
		Untyped:   false,
	},
	TypeCoroutine: {
		TypeKind:  TypeCoroutine,
		Name:      "Coroutine",
		Display:   "",
		Bits:      0,
		Integer:   false,
		Primitive: false,
		Unsigned:  false,
		Float:     false,
		Untyped:   false,
	},
}

var typeKindValues = []TypeKind{
	TypeInvalid,
	TypeVoid,
	TypeI8,
	TypeI16,
	TypeI32,
	TypeI64,
	TypeU8,
	TypeU16,
	TypeU32,
	TypeU64,
	TypeF32,
	TypeF64,
	TypeString,
	TypeCString,
	TypeBool,
	TypeStruct,
	TypeArray,
	TypeFunc,
	TypeCFunc,
	TypePointer,
	TypeMap,
	TypeEnum,
	TypeUntypedInt,
	TypeUntypedFloat,
	TypeUntypedNil,
	TypeMultiReturn,
	TypeGenerator,
	TypeCoroutine,
}

var typeKindByName = map[string]TypeKind{
	"invalid":      TypeInvalid,
	"void":         TypeVoid,
	"i8":           TypeI8,
	"i16":          TypeI16,
	"i32":          TypeI32,
	"i64":          TypeI64,
	"u8":           TypeU8,
	"u16":          TypeU16,
	"u32":          TypeU32,
	"u64":          TypeU64,
	"f32":          TypeF32,
	"f64":          TypeF64,
	"string":       TypeString,
	"cstring":      TypeCString,
	"bool":         TypeBool,
	"struct":       TypeStruct,
	"array":        TypeArray,
	"func":         TypeFunc,
	"cfunc":        TypeCFunc,
	"pointer":      TypePointer,
	"map":          TypeMap,
	"enum":         TypeEnum,
	"untypedint":   TypeUntypedInt,
	"untypedfloat": TypeUntypedFloat,
	"untypednil":   TypeUntypedNil,
	"multireturn":  TypeMultiReturn,
	"generator":    TypeGenerator,
	"coroutine":    TypeCoroutine,
}

// Values returns every declared value in declaration order.
func (c TypeKindContainer) Values() []TypeKind {
	out := make([]TypeKind, len(typeKindValues))
	copy(out, typeKindValues)
	return out
}

// Infos returns every declared value's metadata in declaration order.
func (c TypeKindContainer) Infos() []TypeKindInfo {
	out := make([]TypeKindInfo, len(typeKindValues))
	for i, v := range typeKindValues {
		out[i] = typeKindInfos[v]
	}
	return out
}

// Len returns the number of declared values.
func (c TypeKindContainer) Len() int {
	return len(typeKindValues)
}

// All iterates every declared value in declaration order.
func (c TypeKindContainer) All() iter.Seq[TypeKind] {
	return func(yield func(TypeKind) bool) {
		for _, v := range typeKindValues {
			if !yield(v) {
				return
			}
		}
	}
}

// FromWire converts a raw wire value, reporting whether it is declared.
func (c TypeKindContainer) FromWire(w int) (TypeKind, bool) {
	v := TypeKind(w)
	if uint64(v) >= uint64(len(typeKindInfos)) {
		var zero TypeKind
		return zero, false
	}
	return v, true
}

// FromWireUnsafe converts a raw wire value, assuming it's declared.
func (c TypeKindContainer) FromWireUnsafe(w int) TypeKind {
	return TypeKind(w)
}

// Parse resolves a value by name, case-insensitively.
func (c TypeKindContainer) Parse(s string) (TypeKind, error) {
	if v, ok := typeKindByName[strings.ToLower(strings.TrimSpace(s))]; ok {
		return v, nil
	}
	var zero TypeKind
	return zero, fmt.Errorf("unknown TypeKind: %q", s)
}

// TryGetInfo returns the metadata for v, and whether v is a declared value.
func (v TypeKind) TryGetInfo() (TypeKindInfo, bool) {
	if uint64(v) >= uint64(len(typeKindInfos)) {
		return TypeKindInfo{}, false
	}
	return typeKindInfos[v], true
}

// Info returns the metadata for v, and whether v is a declared value.
func (v TypeKind) Info() TypeKindInfo {
	i, _ := v.TryGetInfo()
	return i
}

func (v TypeKind) Valid() bool {
	return uint64(v) < uint64(len(typeKindInfos))
}

func (v TypeKind) Wire() int {
	return int(v)
}

func (v TypeKind) Name() string {
	return v.Info().Name
}

func (v TypeKind) String() string {
	if i, ok := v.TryGetInfo(); ok {
		return i.Name
	}
	return fmt.Sprintf("TypeKind(%d)", int(v))
}

func (v TypeKind) Display() string {
	return v.Info().Display
}

func (v TypeKind) Bits() int {
	return v.Info().Bits
}

func (v TypeKind) Integer() bool {
	return v.Info().Integer
}

func (v TypeKind) Primitive() bool {
	return v.Info().Primitive
}

func (v TypeKind) Unsigned() bool {
	return v.Info().Unsigned
}

func (v TypeKind) Float() bool {
	return v.Info().Float
}

func (v TypeKind) Untyped() bool {
	return v.Info().Untyped
}

// IterPrimitive iterates each declared value's Primitive in declaration order.
func (c TypeKindContainer) IterPrimitive() iter.Seq[bool] {
	return func(yield func(bool) bool) {
		for _, v := range typeKindValues {
			if !yield(typeKindInfos[v].Primitive) {
				return
			}
		}
	}
}

// IterUntyped iterates each declared value's Untyped in declaration order.
func (c TypeKindContainer) IterUntyped() iter.Seq[bool] {
	return func(yield func(bool) bool) {
		for _, v := range typeKindValues {
			if !yield(typeKindInfos[v].Untyped) {
				return
			}
		}
	}
}

// IterInteger iterates each declared value's Integer in declaration order.
func (c TypeKindContainer) IterInteger() iter.Seq[bool] {
	return func(yield func(bool) bool) {
		for _, v := range typeKindValues {
			if !yield(typeKindInfos[v].Integer) {
				return
			}
		}
	}
}

// IterUnsigned iterates each declared value's Unsigned in declaration order.
func (c TypeKindContainer) IterUnsigned() iter.Seq[bool] {
	return func(yield func(bool) bool) {
		for _, v := range typeKindValues {
			if !yield(typeKindInfos[v].Unsigned) {
				return
			}
		}
	}
}

// IterFloat iterates each declared value's Float in declaration order.
func (c TypeKindContainer) IterFloat() iter.Seq[bool] {
	return func(yield func(bool) bool) {
		for _, v := range typeKindValues {
			if !yield(typeKindInfos[v].Float) {
				return
			}
		}
	}
}
