// Code generated by enumgen from trivia_kind.yml. DO NOT EDIT.

package lexer

import (
	"fmt"
	"iter"
	"strings"
)

// TriviaKind is a uint8-wide identifier. The zero-cost conversion TriviaKind(x) is
// intentional: the underlying value is the wire value.
type TriviaKind uint8

const (
	TriviaKindWhitespace   TriviaKind = 0
	TriviaKindLineComment  TriviaKind = 1
	TriviaKindBlockComment TriviaKind = 2
)

type TriviaKindContainer struct {
	Whitespace   TriviaKind
	LineComment  TriviaKind
	BlockComment TriviaKind
}

// TriviaKinds is the entry point for the TriviaKind enum.
var TriviaKinds = TriviaKindContainer{
	Whitespace:   TriviaKindWhitespace,
	LineComment:  TriviaKindLineComment,
	BlockComment: TriviaKindBlockComment,
}

// TriviaKindInfo is the static metadata attached to a TriviaKind.
type TriviaKindInfo struct {
	TriviaKind
	Name string
}

var triviaKindInfos = map[TriviaKind]TriviaKindInfo{
	TriviaKindWhitespace: {
		TriviaKind: TriviaKindWhitespace,
		Name:       "Whitespace",
	},
	TriviaKindLineComment: {
		TriviaKind: TriviaKindLineComment,
		Name:       "LineComment",
	},
	TriviaKindBlockComment: {
		TriviaKind: TriviaKindBlockComment,
		Name:       "BlockComment",
	},
}

var triviaKindValues = []TriviaKind{
	TriviaKindWhitespace,
	TriviaKindLineComment,
	TriviaKindBlockComment,
}

var triviaKindByName = map[string]TriviaKind{
	"whitespace":   TriviaKindWhitespace,
	"linecomment":  TriviaKindLineComment,
	"blockcomment": TriviaKindBlockComment,
}

// Values returns every declared value in declaration order.
func (c TriviaKindContainer) Values() []TriviaKind {
	out := make([]TriviaKind, len(triviaKindValues))
	copy(out, triviaKindValues)
	return out
}

// Infos returns every declared value's metadata in declaration order.
func (c TriviaKindContainer) Infos() []TriviaKindInfo {
	out := make([]TriviaKindInfo, len(triviaKindValues))
	for i, v := range triviaKindValues {
		out[i] = triviaKindInfos[v]
	}
	return out
}

// Len returns the number of declared values.
func (c TriviaKindContainer) Len() int {
	return len(triviaKindValues)
}

// All iterates every declared value in declaration order.
func (c TriviaKindContainer) All() iter.Seq[TriviaKind] {
	return func(yield func(TriviaKind) bool) {
		for _, v := range triviaKindValues {
			if !yield(v) {
				return
			}
		}
	}
}

// FromWire converts a raw wire value, reporting whether it is declared.
func (c TriviaKindContainer) FromWire(w uint8) (TriviaKind, bool) {
	v := TriviaKind(w)
	_, ok := triviaKindInfos[v]
	return v, ok
}

// FromWireUnsafe converts a raw wire value, assuming it's declared.
func (c TriviaKindContainer) FromWireUnsafe(w uint8) TriviaKind {
	return TriviaKind(w)
}

// Parse resolves a value by name, case-insensitively.
func (c TriviaKindContainer) Parse(s string) (TriviaKind, error) {
	if v, ok := triviaKindByName[strings.ToLower(strings.TrimSpace(s))]; ok {
		return v, nil
	}
	var zero TriviaKind
	return zero, fmt.Errorf("unknown TriviaKind: %q", s)
}

// TryGetInfo returns the metadata for v, and whether v is a declared value.
func (v TriviaKind) TryGetInfo() (TriviaKindInfo, bool) {
	i, ok := triviaKindInfos[v]
	return i, ok
}

// Info returns the metadata for v, and whether v is a declared value.
func (v TriviaKind) Info() TriviaKindInfo {
	return triviaKindInfos[v]
}

func (v TriviaKind) Valid() bool {
	_, ok := triviaKindInfos[v]
	return ok
}

func (v TriviaKind) Wire() uint8 {
	return uint8(v)
}

func (v TriviaKind) Name() string {
	return triviaKindInfos[v].Name
}

func (v TriviaKind) String() string {
	if i, ok := triviaKindInfos[v]; ok {
		return i.Name
	}
	return fmt.Sprintf("TriviaKind(%d)", uint8(v))
}
